### ISSUE TITLE
Crashing all the time, consuming over 100% CPU

### ISSUE THREAD

**Issue by SEXXES** [deanoemcke/thegreatsuspender#813] opened 2018-11-12 16:42 UTC
### Specifications:
 * Extension version: 7.0.109
 * Browser & version: Version 70.0.3538.77
 * Operating system & version: OS X 10.14.1

Shit-extension is crashing all the time, ok I have over 3000 taps open, so what?
24Gb RAM should be enough to handle that and what use has the extension anyway if its not working?

by the way: no problems with FF build-in tap suspension

**Comment by liamjohnston** [comment] 2018-11-12 22:01
First of all, if you don't like the extension, don't use it. 

Have you tried the latest dev build? Not on the chrome store yet. Has some performance improvements.

**Comment by deanoemcke** [comment] 2018-11-14 08:02
@SEXXES definitely check out the latest dev version. there was a bug that affected CPU performance in 7.0.109 which has been fixed.

**Comment by deanoemcke** [comment] 2018-11-14 08:05
Closing as duplicate of #793

**Closed by deanoemcke** 2018-11-14 08:05 UTC
