### ISSUE TITLE
Whatsapp doesn't suspend?

### ISSUE THREAD

**Issue by jonj68** [deanoemcke/thegreatsuspender#234] opened 2015-06-11 11:28 UTC
Hi - the app suspends all open tabs but for some reason it won't suspend whatsapp web.  Any idea why?

**Comment by DanAtkinson** [comment] 2015-06-18 11:29
I do not have this issue. I opened web.whatsapp.com, waited and it suspended by itself. I also tried it with the suspend all tabs functionality and it too suspended the web.whatsapp.com site.

Is it possible that you have whitelisted it by mistake?

![image](https://cloud.githubusercontent.com/assets/23440/8230145/4c876fce-15b5-11e5-9c07-39f32c36a591.png)

**Comment by jonj68** [comment] 2015-06-18 11:39
Hi Dan – thanks for getting back to me.  No problem suspending when I click suspend all tabs.  Just seems as if I stay on that tab and walk away from the computer it never suspends (I can leave it for hours)

**Comment by DanAtkinson** [comment] 2015-06-18 11:41
Hi,

This is intended functionality. The extension will not suspend active tabs.

Thanks, Dan

**Comment by jonj68** [comment] 2015-06-18 11:44
Ah – got it.  I guess I have that tab usually as the active one.  That makes sense.  Thanks so much...love the extension.

**Comment by DanAtkinson** [comment] 2015-06-18 11:46
Cool. If you think that the issue is resolved/addressed, please can you close it?

Otherwise it requires the developer to close.

Thanks, Dan (not the developer!) :)

**Comment by jonj68** [comment] 2015-06-18 11:49
Done!

**Closed** 2015-06-18 11:49 UTC

**Comment by deanoemcke** [comment] 2015-07-03 05:02
@DanAtkinson thanks for handling this one :)
