### ISSUE TITLE
The Great Suspender Crashes after some time

### ISSUE THREAD

**Issue by mamartins** [deanoemcke/thegreatsuspender#86] opened 2014-03-22 23:26 UTC
After some time of google chrome usage the great suspender always crashes. I disabled all other extensions and relaunched browser and this still happens.

I'm on Chrome dev branch

**Comment by deanoemcke** [comment] 2015-01-22 12:40
Duplicate of issue #30.
If you continue to encounter this problem, please use this other issue thread.

**Closed by deanoemcke** 2015-01-22 12:40 UTC
