### ISSUE TITLE
Auto-unsuspend must not unsuspend manually suspended tab while it's still active

### ISSUE THREAD

**Issue by lainverse** [deanoemcke/thegreatsuspender#282] opened 2015-08-29 06:25 UTC
To reproduce enable automatic unsuspension in the options and then suspend any tab. It will be immediatelly unsuspended unless you leave it while it's being suspended.

Manually suspended tab must not unsuspend unless it lost focus and regained it once more.

**Comment by shirtandtieler** [comment] 2015-10-13 01:34
I second this issue :+1: . Currently you only have half a second to switch tabs/close the browser before it unsuspends again

**Comment by deanoemcke** [comment] 2015-11-13 04:55
Duplicate of #274. And has now been fixed!

**Closed by deanoemcke** 2015-11-13 04:55 UTC
