### ISSUE TITLE
Feature Request/Idea: Alert for tab that is using excessive resources

### ISSUE THREAD

**Issue by MichaelWRitchie** [deanoemcke/thegreatsuspender#497] opened 2017-04-26 15:36 UTC
It would be great to have a little pop-up box let you know which tab is using excessive resources then give the option to suspend, close, or ignore (for future alerts) the tab. For example, on my laptop, I can tell that a web application is using a lot of resources even before the UI response slows down because my fan will come on (to cool the maxed out processor). On Windows, you can figure out which process is using the most resources with Task Manager. In certain cases, say with Google Maps, you expect the heavy load and want to allow the application to grab as much as possible. In other cases, say a particularly spammy content website, you want to know which tab is grabbing 90% of the resources so you can suspend or close the tab.  A good UX would be something appeared out of the way and slowly faded away if you ignored it.

**Comment by piotrowski** [comment] 2017-06-03 16:25
Chrome also has a great task manager which shows memory and other resource usage.

You could probably create an extension that hooks in there and lets you disable tabs from there, or get the data from it out inside a context menu on tabs - but that would better be implemented in an additional extension and not in the main great suspender extension.

**Comment by deanoemcke** [comment] 2017-07-25 18:19
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/448
See that issue for my comments on this.

**Closed by deanoemcke** 2017-07-25 18:19 UTC
