### ISSUE TITLE
Needs to have better URLs for history/remote browser tab history

### ISSUE THREAD

**Issue by mappel** [deanoemcke/thegreatsuspender#166] opened 2015-03-23 23:40 UTC
e.g., chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#uri=https://mail.google.com/mail/u/1/#inbox shows up as "Suspended Tab" rather than anything useful to identify this or differentiate it such as "Inbox" or "Gmail". On remote Chrome browsers like iOS Chrome without extensions, this is unworkable. On remote Chromes with thegreatsuspender installed, history still says "Suspended Tab" but opens the original suspended URL offering to resurrect it upon click.

**Comment by deanoemcke** [comment] 2015-03-24 05:31
This has been fixed in the latest version (v6.15). Will be available in the chrome webstore shortly.
Duplicate of issue #164

**Closed by deanoemcke** 2015-03-24 05:31 UTC

**Comment by mappel** [comment] 2015-03-24 12:51
Thank you
