### ISSUE TITLE
New promise errors being generated

### ISSUE THREAD

**Issue by CollinChaffin** [deanoemcke/thegreatsuspender#763] opened 2018-09-23 02:04 UTC
Alpha commit d993b3b generating a LOT of these:

![snag_9-22-2018_20-55-41](https://user-images.githubusercontent.com/9301483/45923421-140ecf00-beab-11e8-8492-79eb24e0a030.png)

What "receiving end" is TGS attempting to "connect" to?

**Comment by deanoemcke** [comment] 2018-09-24 15:44
@CollinChaffin This should be fixed in the latest master.
The promise rejection is expected. It is caused by attempting to send a message to the content script of a tab after the extension has been restarted. In this instance, the content script is no longer reachable. 
This code is specifically there to test for this and reinject the content script if necessary.

The uncaught promise was a bug that has been fixed in the latest master.

**Closed** 2019-02-06 04:05 UTC
Labels: waiting-on-release
