### ISSUE TITLE
Feature Request: Live TV Tabs: Keep Minimum Internet Bandwidth on Inactive Tabs

### ISSUE THREAD

**Issue by figo12** [deanoemcke/thegreatsuspender#243] opened 2015-06-23 18:50 UTC
Hi it would be great if there is a way to leave a minimum amount of internet bandwidth on Live TV related inactive tabs (Such as Watch CNN, Watch TBS, etc)

This way when going back to the inactive Live TV Tab, video feed will still be there and all internet bandwidth should apply when tab is active.

Right now when going back to a suspended tab, live video link needs to load from scratch.

With this feature request, changing live TV channel tabs will be as quickly as watching Cable TV.

Thanks!!

**Comment by Diablo-D3** [comment] 2015-06-29 01:30
Chrome unlikely provides any API to do this.

**Comment by figo12** [comment] 2015-06-29 20:00
Thanks for the info!

On Sun, Jun 28, 2015 at 7:30 PM, Patrick McFarland <notifications@github.com

**Comment by deanoemcke** [comment] 2017-10-24 06:34
Possible duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/589

**Closed by deanoemcke** 2017-10-24 06:34 UTC
