### ISSUE TITLE
Stop opening welcome tab whenever opening new Incognito window

### ISSUE THREAD

**Issue by truth1ness** [deanoemcke/thegreatsuspender#412] opened 2016-06-30 06:16 UTC
When you open a new Incognito Window it keeps opening an extra tab with the "The Great Suspender :: Welcome!" first time introduction message which is really annoying. It seems that the extension thinks it's being used for the first time whenever an Incognito window is opened. Please fix this or let me know if there is a way to disable the welcome tab.

**Comment by deanoemcke** [comment] 2017-07-27 03:43
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/182

**Closed by deanoemcke** 2017-07-27 03:43 UTC
