### ISSUE TITLE
suspend other tabs issue

### ISSUE THREAD

**Issue by dbcdcw** [deanoemcke/thegreatsuspender#203] opened 2015-05-19 15:02 UTC
when i click the button 'suspend other tabs' . it will suspend all tabs with the one i don't want suspend

**Comment by deanoemcke** [comment] 2015-05-19 16:46
can you please be a bit more specific about the issue you are having? are you saying that the active tab is also being suspended when you click this button?

**Comment by MrMormon** [comment] 2015-08-04 23:18
This is happening to me quite often as well.

**Comment by deanoemcke** [comment] 2015-08-11 03:27
Closing as duplicate of #273

**Closed by deanoemcke** 2015-08-11 03:27 UTC
