### ISSUE TITLE
Feature Request: Suspend ALL tabs when Chrome closes

### ISSUE THREAD

**Issue by iakoboss7** [deanoemcke/thegreatsuspender#538] opened 2017-06-17 22:10 UTC
Is it possible to make an option to automatically suspend ALL tabs when i close chrome?

**Comment by H0R1Z0N** [comment] 2017-06-22 20:33
It's pretty already done, kill chrome from the windows task manager, when you open it back, right click on the plugin, option, go to session tab and click resuspend on your last session.

**Comment by iakoboss7** [comment] 2017-06-22 20:58
i would have to do that everytime sadly.

its faster i think if i just click suspend other tabs and close/open chrome.

ofc if it would do it automatically it would be the best.

**Comment by H0R1Z0N** [comment] 2017-06-22 21:14
Just saying doing this's way more failproof that the one integrated on chrome, chrome's doing a bad job when you have 15 windows with 300+ tabs.

**Comment by deanoemcke** [comment] 2017-10-24 02:36
Unfortunately, there is no reliable way to detect when chrome closes. The options that do exist, do not allow time for an extension to do any async action (such as suspending or unsuspending tabs).

Here is the relevant chrome bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=30885

**Comment by deanoemcke** [comment] 2018-09-02 01:46
Duplicate of #700

**Closed by deanoemcke** 2018-09-02 01:46 UTC
Labels: feature, wontfix
