### ISSUE TITLE
Pinned tabs getting suspended and substituted

### ISSUE THREAD

**Issue by LairBob** [deanoemcke/thegreatsuspender#280] opened 2015-08-21 12:57 UTC
I've selected the option for "Do Not Suspend Pinned Tabs", and it normally works fine, but I've run into a new issue recently where if I put my Mac to sleep, then when I wake it back up, the content for most of the pinned tabs has been replaced by the suspended tab to its right.

Example Scenario:
- I have the front page of nytimes.com pinned
- I open several articles into new tabs
- If I just leave the browser window open in the background long enough, all the articles will be suspended, but not the pinned tab
- As long as I leave the computer on, everything continues to act correctly
- I put my MacBook Pro (running Yosemite 10.10.5) to sleep
- When I wake it back up, there is still a pinned tab in my browser, but it's no longer the active NYT homepage -- it's a suspended version of the first article to the right of the pinned tab. (Basically, exactly what's in the tab to its right.)

This isn't limited to the NYT site -- as far as I can tell, it happens to just about any pinned site. 

I'm running Chrome Version 45.0.2454.37 beta (64-bit)

**Comment by PedroC88** [comment] 2015-09-04 23:28
To add more information to this issue (as I'm having the same):

* Any other tab opened from the pinned tab will also change to the right-most tab of the pinned one
* It doesn't necessarily happen if the computer goes to sleep, in my case it happens if I leave it alone for long enough (I haven't noticed if it happens while using it or when Windows locks the screen).
* It's not Mac related, I'm running Windows 8 (build 9600)
* I started noticing it today, after updating Chrome yesterday from v43 to v45 ("45.0.2454.85 m" specifically)

Kudos!

**Comment by voznik** [comment] 2015-09-06 05:03
it happens every day on Ubuntu 15.04 Chrome 46 beta (64-bit) (when Chrome updated to 46). it's very hard to restore all opened & suspended google search tabs when they became identical to 1st...
please, help us!

**Comment by atelier186** [comment] 2015-09-07 23:09
This is happening to me frequently on current Chrome on Mac.  Does seem to be mostly pinned tabs, but I'm not sure if it exclusively happens with those.  Very problematic.

**Comment by richardmtl** [comment] 2015-09-08 13:03
Possible duplicate of #278?

**Comment by LairBob** [comment] 2015-09-08 13:43
It might well be the same thing as #278 -- the behavior is certainly similar -- but the folks in that thread seem to be seeing the problem happen while their browsers are open and active, while I've been seeing the issue crop up very consistently when I put the computer to sleep and wake it up again.

**Comment by koehntopp** [comment] 2015-09-09 11:09
Same here - for me it's usually the Twitter tab (actually, _only_ the twitter.com tab) which gets replaced by up to 4 (!) copies of the tab right next to it.

**Comment by deanoemcke** [comment] 2015-09-10 03:43
I everyone. As mentioned in issue #278, I have tried to replicate this issue but am unable to. Can anyone confirm if it is still happening, and if so, check the version of chrome and the OS you are using?
Thanks.

**Comment by Nemquae** [comment] 2015-09-10 10:05
This keeps happening for me and I'm using Chrome version 45.0.2454.85 on Windows 7.  Quite frustrating when I open chrome and my saved tabs are mostly wrong.

**Comment by LairBob** [comment] 2015-09-10 17:22
I'm still seeing it, with Chrome Version 46.0.2490.22 beta (64-bit), on Mac 10.10.5

**Comment by deanoemcke** [comment] 2015-09-16 15:26
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

Feedback on any issues with this new version would be greatly appreciated.

**Closed** 2015-09-26 05:34 UTC
