### ISSUE TITLE
Google Maps (and some others) fails with too many gsScrollPos

### ISSUE THREAD

**Issue by alberthdev** [deanoemcke/thegreatsuspender#573] opened 2017-08-18 03:00 UTC
This seems to happen with a long-running Chrome, with many Google related tabs open. When opening Google Maps, the map images themselves refuse to load. The Developer Console indicates that Google is returning a HTTP invalid request error, due to too many gsScrollPos cookies stored for their domain. Removing a good chunk of those cookies resolves this issue.

Using the latest The Great Suspender v6.30 (webstore).

**Comment by deanoemcke** [comment] 2017-08-18 15:28
This is essentially a duplicate of this issue: https://github.com/deanoemcke/thegreatsuspender/issues/537

There will be a new release on the webstore soon to address this issue. Sorry for the inconvenience.

**Closed by deanoemcke** 2017-08-18 15:28 UTC

**Comment by jellonek** [comment] 2018-02-19 11:50
Can you give an approximation of time when this issue will be addressed?

**Comment by higstar** [comment] 2018-03-05 01:27
Is there a workaround for this?  i.e. set maps to no suspend?

**Comment by deanoemcke** [comment] 2018-03-12 05:29
@higstar I imagine that if you cleared your cookies and then whitelisted maps, you would not encounter this problem anymore.

@jellonek My current optimistic timeline is April. Fingers crossed.

**Comment by alystair** [comment] 2018-07-25 23:44
Any update? I just googled for "gsScrollPos" and found this, go figure it was caused by this extension...

**Comment by deanoemcke** [comment] 2018-08-15 04:37
Keep an eye on https://github.com/deanoemcke/thegreatsuspender/issues/537 for updates.
I'm pushing really hard for the release right now.

**Comment by Ratismal** [comment] 2018-09-05 23:40
So, this issue has been open for almost a year. I know that for me, personally, it's really annoying to deal with - every so often, I have to open content inspector and delete all of the hundreds of cookies TGS created. Which is a shame, since otherwise the extension is really good.

The good news is, while I don't have a fix, I have a solution! I created a simple userscript (for tampermonkey, greasemonkey, etc) which deletes all cookies named `gsScrollPos-X` when you open any page.

I hope that it provides some much-needed relief for you all.

Link: https://github.com/Ratismal/tgs_cookie_killer

**Comment by rannmann** [comment] 2018-12-24 20:06
It's not ideal, but I run this whenever the maps stop loading:

```
function clearGSScrollCookies() {
    var cookies = document.cookie.split(';');
    for(var i = 0; i < cookies.length; i++) {
        var cookieName = cookies[i].trim();
        if (cookieName.match(/^gsScrollPos\-/)) { 
            console.log("Deleting " + cookieName);
            document.cookie = cookieName + '=; Max-Age=-99999999;';
        }
    }
}

clearGSScrollCookies();
```

**Comment by luixal** [comment] 2019-03-19 17:45
Hey @rannmann , that works like a charm! Thanks!

**Comment by frederickjh** [comment] 2019-04-05 10:10
> It's not ideal, but I run this whenever the maps stop loading:  . . .

@rannmann Where do you add run that code?

**Comment by DaveKap** [comment] 2019-04-14 07:50
This is still a problem and I still hate it.

**Comment by frederickjh** [comment] 2019-04-14 14:25
Thanks @Ratismal for the user script!

**Comment by Jollfye** [comment] 2019-04-15 01:28
@frederickjh, @DaveKap hm if u still have this gsScrollPos issue I think u r using now old 6.30 TGS extension version, a lot was fixed since then, including this bug, I suggest u to update to latest Chrome Web Store 7.1.0 version as I wrote bout it [here](https://github.com/deanoemcke/thegreatsuspender/issues/905#issuecomment-476802818).

**Comment by DaveKap** [comment] 2019-04-15 01:57
> @luixal, @frederickjh, @DaveKap hm if u still have this gsScrollPos issue I think u r using now old 6.30 TGS extension version, a lot was fixed since then, including this bug, I suggest u to update to latest Chrome Web Store 7.1.0 version as I wrote bout it [here](https://github.com/deanoemcke/thegreatsuspender/issues/905#issuecomment-476802818).

 Thank you for this! I had no idea my version was out of date. Why the hell isn't the extension auto-updating?

**Comment by frederickjh** [comment] 2019-04-15 06:33
@Jollfye the extension would not upgrade to the new version without first uninstalling the old version in my case. Waiting to see if this fixes it as I could go days or weeks before the gsScrollPos issue would rear its ugly head.

**Comment by Jollfye** [comment] 2019-04-15 08:02
@DaveKap, @frederickjh, yep that not auto-updating thing, only manually or through uninstall, I met it too (long ago) but I guess actual developer @deanoemcke may has a clue why.. and yes, I think the bug should be gone the moment u run latest TGS extension version coz now scroll position is being stored in suspended tab's url, not in cookies as before, so gsScrollPos should also be gone and u should never see it again 😅

**Comment by Avamander** [comment] 2019-06-24 14:46
For some reason I hadn't still gotten the new version from Chrome web store. Had to manually uninstall and reinstall.

**Comment by frederickjh** [comment] 2019-06-24 16:18
I haven't see this issue rear its ugly head since my last post about updating in April. I consider it fixed.

**Comment by Avamander** [comment] 2019-06-24 16:44
It's not fixed if people are not getting the update.

**Comment by frederickjh** [comment] 2019-06-26 07:07
@Avamander That is another related issue that the update will not install without first uninstalling The Great Suspender chrome extension. 

If that is something that cannot be fixed, so that the extension can auto update, at the very least the information that you need to uninstall to upgrade to the newest version should be added to the extension's page on the [chrome web store](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg).

Do we know what version will not update automatically but needs to be uninstalled first?  I see that the OP of this issue was on version 6.30.  I am currently on version v7.1.0, but do not remember what version I was on before I uninstalled.

If we can figure out the version that I can create an issue to have that information added to [the great suspender chrome web store page](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg).
