### ISSUE TITLE
Issue/Request about tabs with music playing

### ISSUE THREAD

**Issue by tobyponz** [deanoemcke/thegreatsuspender#107] opened 2014-07-07 10:44 UTC
Hi,

I don't want to whitelist youtube.com or similar sites because it often happens that I first open many videos than let some time pass and watch them sometime later, or maybe I need to show somebody a video later at home and I need it to be suspended.

When I want to only listen to music on youtube or similars, though, I often get the tab suspended mid-song (I often use playlists, and have an incactivity time of 30mins) and then I have to completely close the tab to get it to work because if I just unsuspend it it will suspend again after a brief period of time.

So I'm here to ask if you could make a check in the settings (so that it remains a non forced option) to not suspend tabs while audio is playing from them.

Is it possible? Is it too personal of an issue?

**Comment by lainverse** [comment] 2015-03-26 12:40
I prefer to suspend even pinned tabs since I don't want at least half of them to be running all the time.
I also don't think it's hard to detect does tab plays music or not. At least this extensions does something similar: https://chrome.google.com/webstore/detail/mutetab/nmkbaaijgpppbokgnhhoakihofedkgcc

I think there should be some kind of API for that. At least browser knows for sure which tabs produce any sounds and shows an extra icon on such tabs.

So, I think all tabs which produce sound non-stop should be automatically temporary whitelisted. They shouldn't be whitelisted if they produce sound only occasionally, though. For example pinned Outlook and Gmail web interfaces may produce sounds for new messages but if they set to be auto-suspended then they should be.

Also tab must not be auto-suspended within ~15 seconds after sound stopped to play since it could be due to internet speed, data buffering or switching between tracks in the playlist.

**Comment by deanoemcke** [comment] 2015-05-10 05:44
Closed as duplicate of #28

**Closed by deanoemcke** 2015-05-10 05:44 UTC
