### ISSUE TITLE
feature request: unsuspend with [spacebar]

### ISSUE THREAD

**Issue by LiNk-NY** [deanoemcke/thegreatsuspender#460] opened 2016-12-23 04:58 UTC
This should be pretty easy to implement but I'm not sure how. 
Would be great if you can add this feature or someone with know-how can send a pull request. 
Thanks!

**Comment by deanoemcke** [comment] 2017-07-25 18:46
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/522

**Closed by deanoemcke** 2017-07-25 18:46 UTC
