### ISSUE TITLE
Issues with Session History

### ISSUE THREAD

**Issue by dckidd** [deanoemcke/thegreatsuspender#159] opened 2015-03-16 13:47 UTC
It looks like my extension was just upgraded to v6.12.  In the process, it looks like a bunch of my saved tabs were not restored in Chrome.  I see some options in Session History for the extension including the saved session I'm assuming it did as part of the upgrade, but none of the links seem to be working.  Any ideas why that may be and how I can get back all of the suspended tabs I had prior to the upgrade?  Thanks.

**Comment by weslymoore** [comment] 2015-03-16 16:59
Same problem here.  Session saved 16 March 2015 with numerous open tabs, apparently (based on timing) as part of the extension upgrade.  Only a small percentage of tabs opened again afterward.  Links to reopen, export, save seem to do nothing.

**Comment by deanoemcke** [comment] 2015-03-17 11:42
@dckidd @weslymoore hey guys. really sorry that the upgrade process did not go smoothly for you. i have been aware for a long time that this update was going to be problematic for some people - this is because chrome automatically updates extensions without warning and in doing so, closes and restarts the extension. this causes all currently suspended tabs to close and the old version of the extension had no way of knowing which tabs they were.
i have identified a few issues in the latest version that have caused the session management tab to not operate correctly. this has been corrected in a new version (just pushed live - v6.13). it may help you to work out which tabs you lost during the update.
i'd like to also mention that future releases of the extension should be much smoother and all tabs will be restored instantly. 
let me know if you have any questions about this.

**Comment by balachia** [comment] 2015-03-17 19:03
Could you have given a heads up on the upgrade? I'd been using Session Buddy as a session manager and could have at least saved a backup of the session. I use open tabs as working memory, and this upgrade just threw out ~50 tabs.

**Comment by deanoemcke** [comment] 2015-03-17 19:23
there's really no way to let anyone know in advance. active visitors to this gitHub project were aware. and the only other way to let users know is well, via an update of the extension, which is what caused the problem.
i'm aware it's a big pain, which is why i made sure this time round that i can perform a full recovery on subsequent updates. try it out if you want. go into chrome://extensions and then disable the extension (all your suspended tabs will disappear) and then re-enable the extension (all the suspended tabs come back in the same location/windows). it should make subsequent updates seamless for everyone.
as many people are aware on this gitHub project page, this update has been a looooong time coming. this is primarily because i didn't want to put everybody through this pain. and when i did, i wanted to make sure it was going to be worth it. it had to happen at some point. there were some major bugs that needed to be addressed.

**Comment by deanoemcke** [comment] 2015-03-22 08:58
all known session history bugs should be fixed in the most recent version (v6.14).
note: this does not cover tabs lost during the update process - that issue was out of my control for this release, but future releases will not exhibit the same issue.

**Comment by dckidd** [comment] 2015-03-24 17:40
So does that mean we really have no way of identifying the tabs we lost with the v6.12 upgrade?  I'm fine with doing some digging and least being able to know which ones I had with some kind of automated export/restore functionality.  Thanks.

P.S.  It doesn't look like Chrome has pushed either upgrade down to me since 6.12.  I even tried going into developer mode and using the Update Extensions Now button.

**Comment by weslymoore** [comment] 2015-03-26 03:51
I'm in the same boat - still sitting at 6.12.  I too have tried updating extensions manually from developer mode.  Can't begin to understand the update process here.

Is there any way at all to review a list of tabs that were open and saved as a set in session history?  Even if I had to review and decide which ones to open manually, that would be helpful.  Otherwise I've lost 100 tabs that were open when the extension upgraded.  I do so much browsing, it's not possible to review browser history and find them in anything like a reasonable amount of time.  I do see the set of tabs saved in session history, I just can't do anything with it.

**Comment by deanoemcke** [comment] 2015-03-26 11:44
@dckidd @weslymoore 
sorry about the random update process. i'm working on a stable v6.15 and don't want to roll it out across the board until it's ready. until then you'll be stuck on your current version.
however, you should be able to uninstall and then reinstall v6.14 from the chrome webstore. this should be pretty stable.
you should be able to go to the session history section in the settings page and restore any or all tabs from that list. is that not working for you? try after updating to v6.14 and see if that makes a difference.
sorry for the hassle, there really was no way of knowing which tabs were open when the extension upgraded - it only recorded the tabs at the time they were suspended so doesn't know if they were subsequently closed or if they were still open.

**Comment by weslymoore** [comment] 2015-03-30 23:32
I had considered doing an uninstall/reinstall in order to get to v6.14, but I was worried about losing not just currently open/suspended tabs but the session history.  Is that a possibility?  Because as I mentioned earlier I do see a saved session from apparently just before the extension upgrade, which presumably contains the tabs that were open at the time, but the links to restore etc. do nothing.  I'm willing to upgrade to v6.14 if there's no worry about losing the session history, otherwise I guess I may as well wait for v6.15.

**Comment by deanoemcke** [comment] 2015-05-10 02:28
@weslymoore an uninstall/reinstall will lose all your session history (if by session history you mean the sessions listed in the great suspender session tab). 
unfortunately I'm not sure if i'll fully rollout v6.15 to existing users at this point as I'm worried about the impact it has on everybody.
are you still looking for a way to recover your session? if so, I can probably give you some custom code that you can run in a console to recover your tabs which will then allow you to do an uninstall/reinstall without losing anything..

**Comment by dckidd** [comment] 2015-05-11 16:09
@deanoemcke, @weslymoore's comment pretty much mirrors my situation.  I see under Saved Sessions what I assume to be all of the tabs I had prior to the v6.12 upgrade on 3/16.  If doing an uninstall/reinstall will make me lose that session history, I would be interested in trying your custom code to recover the tabs from that session or some other method that at least lets me identify what those were at that time.  Thanks.

**Comment by deanoemcke** [comment] 2015-05-16 06:13
@dckidd just to clarify - in the saved session you can see, do the 'resuspend' and 'reload' buttons not do anything? also, what happens when you click on one of the actual tab links within that session?
are you savvy with the chrome console? it would be great to try to debug the issue - that might be the easiest way to get things working for you.
to debug: on the extension session management page, bring up the console (F12 on your keyboard) and then try to click the 'resuspend' or 'reload' links. you should see some errors come up in red if things aren't working properly. 
copy and paste the errors if possible and we can go from there..

**Comment by Mister-Bill** [comment] 2015-06-23 02:38
I'm also having this problem, or at least it's related to this. I restarted Chrome to update to the latest beta, and when it restarted many of my tabs were gone. I also run the Sidewise extension (for side tabs) and it remembers open tabs and allows an option to restore open tabs. But it didn't have most of them. I gather the issue is that the tabs become invisible to Chrome once this extension puts them to sleep.

Disappointing that this is such an annoying problem since I have been very impressed with this extension otherwise.

**Comment by deanoemcke** [comment] 2015-07-03 05:56
@Mister-Bill what do you see when you go to the extensions 'session management' section? it should retain a more complete view of your tabs including suspended ones.

**Closed** 2015-11-13 04:24 UTC
