### ISSUE TITLE
unable to set options

### ISSUE THREAD

**Issue by gargatok** [deanoemcke/thegreatsuspender#134] opened 2014-10-28 10:40 UTC
Going to settings, I get this error in the console:
Uncaught TypeError: undefined is not a function, options.js line 57
I'm unable to save any settings. I have the newest version of the suspender as of today, and Google Chrome Version 38.0.2125.104 m.

With the same version, I'm unable to unsuspend any of my suspended tabs:
Uncaught TypeError: Cannot read property 'preview' of null gsUtils.js:84
Uncaught TypeError: Cannot read property 'gsTidyUrls' of null gsUtils.js:84
gsUtils.getOption
unsuspendTab suspended.js:151

Any clue how to solve this? Thank you!
All the best,
Gergely

**Comment by rickydeez** [comment] 2015-01-09 20:22
Same issue/error here: 

Uncaught TypeError: Cannot read property 'preview' of null

[gsUtils.js:83] if (typeof settings[prop] === 'boolean') {

**Comment by deanoemcke** [comment] 2015-01-13 13:37
Duplicate of issue: https://github.com/deanoemcke/thegreatsuspender/issues/143
Closing. Please refer to this other issue instead.

**Closed by deanoemcke** 2015-01-13 13:37 UTC
