### ISSUE TITLE
Design of suspended page

### ISSUE THREAD

**Issue by AlexWayfer** [deanoemcke/thegreatsuspender#725] opened 2018-08-23 15:01 UTC
Hello!

Thanks for v7 release.

But with the new version it's harder for me to realize suspended tab (name, domain, image).

I think:
* Site info should be at screen center by horizontal (left is uncomfortable at big screens)
* Favicon can be bigger
* TGS "suspended tab" image can be smaller

How it's now:

![image](https://user-images.githubusercontent.com/6510020/44533371-104a2a00-a6fe-11e8-93aa-34aae090c94e.png)

About how I want:

![image](https://user-images.githubusercontent.com/6510020/44533348-058f9500-a6fe-11e8-9e52-5e7ac43662aa.png)

### Specifications:
 * Extension version: 7.0.104
 * Browser & version: Chromium 68.0.3440.106
 * Operating system & version: Arch Linux

**Comment by alidan** [comment] 2018-08-23 18:34
Personally I want the old color back, the problem with the new colors are they are so close to 'chrome is having issues' colors that it takes a while to realise the page itself is just suspended. 

If I remember right, the top area of the screen could be clicked on without un suspending the tab, I could be wrong as Its something I stopped paying attention to a long time ago and just did it, it was nice to have a section to focus a windows clicking on the chrome interface allowed for 20 pixels of wiggle room while tgs old layout allowed around 300-400 pixels, at least for me

**Comment by AlexWayfer** [comment] 2018-08-23 18:46
> Personally I want the old color back, the problem with the new colors are they are so close to 'chrome is having issues' colors that it takes a while to realise the page itself is just suspended.
>
> If I remember right, the top area of the screen could be clicked on without un suspending the tab, I could be wrong as Its something I stopped paying attention to a long time ago and just did it, it was nice to have a section to focus a windows clicking on the chrome interface allowed for 20 pixels of wiggle room while tgs old layout allowed around 300-400 pixels, at least for me

Totally agree.

**Comment by alidan** [comment] 2018-08-23 19:06
I should also point out that both light and dark theme while they share looks with chrome had an accident pages, also look like other websites dark theme, so If I have a page in the background that I see a bit of the edge, it looks like those sites. The old colors were completely unique to tgs. it's not so much a major issue, as it is an annoyance to unsuspend a tab by accident thinking its something else.

**Comment by AlexWayfer** [comment] 2018-08-23 19:14
> it's not so much a major issue, as it is an annoyance to unsuspend a tab by accident thinking its something else.

Exactly. Thanks for these words, you're describing my experience well.

**Comment by deanoemcke** [comment] 2018-08-23 20:58
@AlexWayfer @alidan  

thanks for the feedback. a couple of counterpoints.

1. i feel like part of your problems are due to your massive screen resolution. i've attached a screenshot of what it looks like for me.

2. the favicon is rendered at original size. if i try to increase that it's going to start looking bad.

3. for the background colour, it's a good point about it looking like a chrome error tab. an alternative for you might be to use the night theme?

4. i'm not 100% sure i understand what you mean about needing a section to focus a window? for me, if i click anywhere on a suspended tab on a window that is NOT in the foreground, it does not action an unsuspend. also, the reason i made the top area clickable for unsuspension was for reasons communicated in this issue: https://github.com/deanoemcke/thegreatsuspender/issues/180
i actually found myself having this problem too. where i would want to unsuspend a tab with the mouse but would end up clicking on the top bar and nothing would happen.

i'm still open to ideas, especially for handling users such as yourself with large screen resolutions. let me know what you think about my comments above.

![image](https://user-images.githubusercontent.com/1051763/44551156-4a163300-a6f4-11e8-8152-b6b7f793c247.png)

**Comment by AlexWayfer** [comment] 2018-08-23 21:11
> i feel like part of your problems are due to your massive screen resolution. i've attached a screenshot of what it looks like for me.

Yeah, cause of this I wrote "left [side] is uncomfortable at big screens". I guessed that this is OK at small screens like notebooks. But at large… you have to rotate you head to the left. :sweat_smile: Almost all web-sites have centered content.

> the favicon is rendered at original size. if i try to increase that it's going to start looking bad.

You can look at my example (I didn't change elements, just CSS and some HTML rearranges). I think Google's favicon is nice.

> i'm not 100% sure i understand what you mean about needing a section to focus a window?

The top gray area is non-clickable:

![image](https://user-images.githubusercontent.com/6510020/44552107-cbd88180-a731-11e8-8fba-ad74695bbed3.png)

> for me, if i click anywhere on a suspended tab on a window that is NOT in the foreground, it does not action an unsuspend.

For me these clicks unsuspend tabs at Linux with Gnome 3 DE.

> also, the reason i made the top area clickable for unsuspension was for reasons communicated in this issue: #180

Good point, but I think we're needing for any non-clickable area.

> i'm still open to ideas, especially for handling users such as yourself with large screen resolutions. let me know what you think about my comments above.

Thanks! I appreciate it.

**Comment by alidan** [comment] 2018-08-24 00:41
I am using dark mode
Light mode is close to googles error when it shows an error happened, dark mode is close to the google isn't displaying a damn thing and is hanging hard 
For reference I am using a 4k 55 inch tv as a monitor, I wanted multiple monitors, and this was the best I could do, that and tvs generally being better than most monitors at this point, so keep that in mind, 

a big part of my problem with the color is this. 
![chrome_2018-08-23_19-10-24](https://user-images.githubusercontent.com/2681758/44558181-57d5b380-a708-11e8-8553-74a202b0004c.png)

each one is a different dark theme site/extension, and being able to tell them apart from the middle one which is tgs at a quick glance isn't easy. I generally have 2 pages open with a sliver in the background seen on a third

Personally, The original two color themes could be implemented as their own theme, like I said above, the original colors for the program are pretty distinctive, I also liked the upper section of the window with a different color, it helped, also, centered for the top bit would likely also be a good thing but its hard to say if its better if there would be 1 solid color. 
possibly a small gradient shift at the top or even user defined colors, though I don't know how much work that would be. hell on this part a user choice if there is a top part or not, if there is a gradient or not, how it connects with the bottom and a user defined color

really all I want is the old dark mode's color back anything more then that is just a nice addition as far as i'm concerned.

**Comment by fwextensions** [comment] 2018-08-24 01:10
A larger favicon can be pulled via `chrome://favicon/size/48/https://google.com`, though there's no guarantee a site has a larger one available.

**Comment by deanoemcke** [comment] 2018-08-24 06:42
Possible redesign: https://github.com/deanoemcke/thegreatsuspender/tree/hotfix/suspended-tab-redesign

**Comment by AlexWayfer** [comment] 2018-08-24 08:59
@deanoemcke, will I loose suspended tabs if replace Chrome Web Store version with the built from sources?

Oh, I found this in the [Installing beta version](https://github.com/deanoemcke/thegreatsuspender/wiki/Installing-beta-version) guide: 

> Disable the existing version of the extension (IMPORTANT: unsuspend all tabs before doing this or they will disappear!)

I think it can be in the README (in the "Build from github" section, maybe).

**Comment by fwextensions** [comment] 2018-08-24 19:17
>  for me, if i click anywhere on a suspended tab on a window that is NOT in the foreground, it does not action an unsuspend. 

I've never seen that behavior in either Win7 or Win10.  Focusing a background window by clicking the bottom area of a suspended tab has always unsuspended it for me.  TGS would need to be checking the tab focus state when handling the click to prevent the default behavior, which is for the page to get the click event. 

macOS handles clicks on background windows differently, and doesn't pass on the click to any of the controls in the window (at least by default, I think).

**Comment by roastchicken** [comment] 2018-08-27 07:51
I can confirm with @fwextensions that clicking on a suspended tab in a window that is not in the foreground unsuspends it exactly as one would expect when clicking on it in the foreground. This is on Windows 10.

**Comment by deanoemcke** [comment] 2018-08-27 19:47
For the ongoing discussion on whether to make the topbar unclickable, please refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/741

I will close this as being mostly implmented with the redesign PR.

**Closed by deanoemcke** 2018-08-27 19:47 UTC
Labels: waiting-on-release

**Comment by uhuhleuh** [comment] 2018-10-04 21:49
Can we have several colors for the suspended page? I have 3 chrome instances already running (3 different google accounts). When they are minimized (Mac OS) I barely can distinguish them. If I could have 3 different colors for the suspended page, it would be a lot easier...

**Comment by deanoemcke** [comment] 2018-10-06 03:11
@uhuhleuh hmmm.. while i agree it would be nice to be able to distinguish easily between different chrome profiles, i feel like that's a bit out of scope of this extensions purpose.

for most users that would just come across as, "you can customise the background colour of your suspended tab page" which is not something i really want people to be able to do (because I don't like custom theming in general).
