### ISSUE TITLE
Tabs playing audio (e.g. Youtube) suspend

### ISSUE THREAD

**Issue by justingiffard** [deanoemcke/thegreatsuspender#445] opened 2016-10-14 23:04 UTC
I noticed that The Great Suspended suspends a tab even if it is playing music. I listen to music streams on Youtube and obviously don't want to whitelist the entire site. Could you possibly add a setting or way of tagging in whitelist that if a tab is playing audio that it doesn't get suspended?

I think MuteTab can detect if a tab is playing audio so maybe you could do it in the same way?

**Comment by seanthebean** [comment] 2017-02-23 20:41
I often listen to music on YouTube too (either music playlists or 8-hr "white noise" videos), and I would really like to see this as well. If it can detect whether the tab is playing audio would allow it to work for any other music streaming service (e.g. Pandora, Amazon Music, etc) as well, without having to whitelist each one individually (thereby allow it to be suspended when you're _not_ actively using it, which would free up more memory).

I think being able to toggle this behavior under Settings would be a nice touch.

**Comment by deanoemcke** [comment] 2017-07-25 18:32
This has already been implemented in v6.30 :)
Duplicate of issue: https://github.com/deanoemcke/thegreatsuspender/issues/28

**Closed by deanoemcke** 2017-07-25 18:32 UTC
