### ISSUE TITLE
Stopped working completely with Chrome v46

### ISSUE THREAD

**Issue by PiNotEqual3** [deanoemcke/thegreatsuspender#312] opened 2015-10-16 07:11 UTC
Unfortunately with Chrome v46 this extension stop working completely. 

After some debugging I see `chrome.windows.getLastFocused({populate: true}, suspendActiveTab);` returns the wrong window. Tried to fix it with `chrome.windows.getCurrent` but that's just the same...

**Comment by PiNotEqual3** [comment] 2015-10-16 08:35
ok, fixed this by updating backgorund.js with:

    //handler for popup clicks
    chrome.extension.onRequest.addListener(
        function (request, sender, sendResponse) {

            chrome.tabs.query({ active: true, currentWindow: true }, function(a)
            {
                if (a && a.length)
                {
                    var windowID = a[0].windowId;
                    if (request.msg === "suspendOne") {
                        chrome.windows.get(windowID, {populate: true}, suspendActiveTab);
                    } else if (request.msg === "suspendAll") {
                        chrome.windows.get(windowID, {populate: true}, suspendAllTabs);

                    } else if (request.msg === "unsuspendAll") {
                        chrome.windows.get(windowID, {populate: true}, unsuspendAllTabs);
                    }
                }
            });
        }
    );

**Comment by PiNotEqual3** [comment] 2015-10-16 08:40
oh, while creating a push request I see the extension here if already fixes and is far away from what is in the chrome extension store. Maybe someone can release an update...

**Comment by dt-rush** [comment] 2015-10-16 21:42
Strange, it seems to be working for me. Which exact functionality was not working? "Suspend This Tab"?

**Comment by dt-rush** [comment] 2015-10-16 21:44
Ah, from looking at the pull request it seems "Suspend Other Tabs" was broken. It's also broken for me at the moment, using Chrome 46 and the The Great Suspender 6.19

**Comment by weiweihuanghuang** [comment] 2015-10-20 07:42
Suspend all tabs doesn't work.
Sometimes suspend this tab doesn't work either

**Comment by PiNotEqual3** [comment] 2015-10-20 07:49
@dt-rush Correct. In my old version all functions did not work but in current build only "Suspend Other Tabs" has this problem. I also added "Suspend All Tabs" if someone is interested I can push that, too.

En Taro Adun! ;)

**Comment by weiweihuanghuang** [comment] 2015-10-20 11:27
@PiNotEqual3 i just upgraded from like v4. suspend all tabs is great—it used to be there… was it taken out?

**Comment by PiNotEqual3** [comment] 2015-10-20 11:54
@weiweihuanghuang It is not in the current master, see [popup.html](https://github.com/deanoemcke/thegreatsuspender/blob/master/src/popup.html) not sure why it was taken out. The function is still named `suspendAllTabs()` but [it is used](https://github.com/deanoemcke/thegreatsuspender/blob/master/src/js/background.js#L217) for "Suspend other tabs"

**Comment by weiweihuanghuang** [comment] 2015-10-21 10:54
@PiNotEqual3 if I change it to:

    function suspendAllTabs() {
        chrome.windows.getLastFocused({populate: true}, function(curWindow) {
            curWindow.tabs.forEach(function (tab) {
                requestTabSuspension(tab, true);
            });
        });
    }
Should that work?

**Comment by PiNotEqual3** [comment] 2015-10-21 11:17
@weiweihuanghuang I am not sure if it returns the full window object. Just give it a go ;)

**Comment by tnorthcutt** [comment] 2015-10-28 21:34
`Suspend all tabs` and `Suspend other tabs` is working for me.

Chrome 46.0.2490.80 (64-bit)
The Great Suspender 6.21

**Comment by lennartcl** [comment] 2015-10-29 02:08
I was having the same problem with

Chrome 46.0.2490.80 (64-bit)
The Great Suspender 4.74

Not sure why I have this old version or how long that hasn't been updated. The "Update extensions now" button in Chrome wouldn't update it, so I uninstalled and reinstalled it. Problem appears to be gone. Any reason to believe not updating can be The Great Suspender's fault? Otherwise at least for me it was just caused by using an old version.

**Comment by deanoemcke** [comment] 2015-11-04 06:06
The issue with 'Suspend other tabs' not working has been fixed in the latest release.
@lennartcl You are correct in assuming that it is the extensions fault that it doesn't automatically update. A long time ago I decided that automatically updating the extension was too risky as it removes all suspended tabs from the users browser. Hence, the extension does not automatically update.

**Comment by xgdgsc** [comment] 2015-12-12 13:17
It is right not to auto update, is there an update notification to inform users of new releases?

**Comment by deanoemcke** [comment] 2017-06-08 16:36
This feature is now available in the chrome webstore on v6.30.

**Closed by deanoemcke** 2017-06-08 16:36 UTC
Labels: fixed, waiting-on-release
