### ISSUE TITLE
Tab icon replaced with extension icon and text replaced with "Suspended Tab"

### ISSUE THREAD

**Issue by nomennescio** [deanoemcke/thegreatsuspender#478] opened 2017-03-06 11:12 UTC
The idea of this extension is great; keep lots of tabs open, while automatically saving memory.

However, I regularly have +- 50 windows with each 20 tabs open, as reference material.
To quickly switch to a needed tab, I first Alt-TAB to a window, then select a tab.
HOWEVER, when using this extension, all suspended tabs will get their tab icon and tab text replaced.
This makes selecting a suspended tab IMPOSSIBLE without going through ALL suspended tabs.

As it now is, the webpage itself shows a text about the page being suspended and needing a reload,
so why not just KEEP the original tab icon and text? That would solve this issue very simply.

**Comment by nomennescio** [comment] 2017-03-06 12:07
Interestingly, it seems this is already PARTIALLY implemented.
If I enable suspending, and set it to 20 seconds, then ALL tabs will be suspended after 20 secs,
and ALL icons and tab texts are replaced. This makes this extensions practically unusable.

HOWEVER, if I now "disable" suspending, by setting the timeout to "never", all icons reappear,
WHILE the webpages are STILL suspended.

Hence, to implement this feature, just do not overwrite tab icons and tab text when suspending it.

If wanted, you can make this into a customizable option.

**Comment by penn5** [comment] 2017-03-13 17:23
I believe this is already FULLY implemented.
After tabs suspend for me, they shortly display "Suspended Tab", but quickly change to the original. The icon is the same but faded.

**Comment by PlayerPL** [comment] 2017-03-19 11:19
Not sure. I have same situation as nomennescio.

**Comment by bja-au** [comment] 2017-06-14 02:14
G'day - I'm having the same problem - didn't happen with the previous version. Is there any way I can install the previous version (6.21??) please? Thanks bja

**Comment by deanoemcke** [comment] 2017-07-25 16:38
This is a bug. Due to the way that tabs are suspended, it is impossible to display the correct icon and title instantly, however, as soon as the page loads, the icon and text *should* be replaced. In normal circumstances this is almost instantaneous.
@nomennescio @PlayerPL @bja-au Are any of you able to check out the chrome developer console on one of the suspended pages that is not updating the icon?
I suspect there will be some errors in the console of these pages. It would be really useful to know what is happening here.

**Comment by liv-in-sky** [comment] 2018-09-21 07:37
hi,

I'm using chrome canary version 71 with great suspender version 7.0.109 - I also have chrome 69 with suspender. in canary I have this issue - After starting canary some of the tab icons have the suspender icon - some not. I have to click the tab and it will change to the right icon. in chrome 69 I don't have this issue.
![suspender](https://user-images.githubusercontent.com/18462890/45866636-c185c380-bd81-11e8-9d78-b13685035dab.png) - Any hints what to do ?

**Comment by fwextensions** [comment] 2018-09-21 20:00
@liv-in-sky, there was a fix for that committed a few weeks ago as part of #719, but I don't think that version has been released yet.  You could try loading the most recent version from master.

**Comment by liv-in-sky** [comment] 2018-09-22 17:47
I was a little bit too fast - It is working after starting the chrome canary browser but after a few hours working with my computer: suddenly some of the tab-icons are dissapeared and the suspender-icon was shown.

**Comment by fwextensions** [comment] 2018-09-23 03:07
@liv-in-sky, this is without restarting the canary build?  Do you have the *Automatic tab discarding* flag set differently between the two versions of Chrome?  Also, which OS are you on?

**Comment by liv-in-sky** [comment] 2018-09-23 08:15
hi ,
- I can't say if I restartet the canary during the day (80% for yes)
- I did some work on my pc and after a few hours the icons where gone - I also have the problem this morning - see picture
![thismorning](https://user-images.githubusercontent.com/18462890/45925625-77cfe100-bf19-11e8-9913-f5c139a21a3c.png)

- chrome canary flag is default - in chrome is enabled - I will change the flag to enable in canary and will give you feedback

**Comment by liv-in-sky** [comment] 2018-09-23 08:18
I restartet -  all Icons are right (flag enable like in regular chrome) - what is the right setting for this flag - enabled or disabled? - both chrome versions now on: enabled

I'm on windows 10 - 64bit

thanx for your help

**Comment by fwextensions** [comment] 2018-09-26 19:14
I thought the default setting would've been enabled, so it's strange that explicitly setting it to enabled made any difference.  But glad it helped.

**Comment by liv-in-sky** [comment] 2018-09-27 09:16
hi
 at the moment - I have to restart chrome canary every morning before all icons are shown. after power on and starting canary - the "regular" icons aren't shown (all have "suspender" icons) - then restart canary - all icons are back - every morning !

**Comment by fwextensions** [comment] 2018-10-03 16:44
Strange.  I used to see that issue on Win7 with the old version of the extension, but I haven't seen it on v110 on Win10.  Have you pulled the latest version from master recently?  And this is working fine on Chrome 69, but not on canary? 

From @deanoemcke's [comment](https://github.com/deanoemcke/thegreatsuspender/issues/478#issuecomment-414537082) above, it sounds like he thought this was fixed, so maybe he can do some more debugging with you.

**Comment by liv-in-sky** [comment] 2018-10-03 18:36
hi

version 7.0.122 and Version 71.0.3568.0 (Offizieller Build) canary (32-Bit) - still have to restart canary  after shwitch on the pc

**Comment by deanoemcke** [comment] 2018-10-04 03:06
@liv-in-sky can you please walk me through your situation in a bit more depth?

beginning at the night before, you have chrome canary open with some tabs:
- how many tabs? in how many windows?
- do you close chrome canary? or power down your computer? or simply close the lid?

then in the morning:
- are you restarting/opening the lid of your computer and canary reappears? or are you manually restarting canary and it is 'continuing where you left off'?

i assume this is the point where you're finding that some tabs do not recover their favicons:
- how are you restarting canary at this point that fixes the issue?

Thanks for the details, it will greatly help me diagnose your issue.

**Comment by liv-in-sky** [comment] 2018-10-04 07:09
the data:
 I open 3 windows - by default - I close the browser with exit to keep the tabs saved.
1: 3 tabs
2: about 30
3: about 20
I have changed canary to 64 bit -  same situation - I did the same in chrome - no problem

"the whole story" - I used chrome - over the time - chrome run very slow and unstable - (I do a lot of research and also open a lot of web-admin tools ) - In order to NOT loose all my settings I decided to install canary. During switch on the PC: At he moment chrome is opening automatically (I don't know why ?:-( ). then I have to open canaryby clicking the icon. only a couple (4 or 5 icons) are shown right. then I exit canary and start it again - all icons are there. overall I have 3 canary windows and one chrome window. I will now try the following: deinstall great suspender on both "chromes" (because of sync). restart the computer - stop chrome - open canary

**Comment by deanoemcke** [comment] 2018-10-04 18:10
hmmm.. i think for simplicity's sake, we can just ignore your normal chrome application. the two shouldn't have any effect on each other.

so you have canary open with 3 windows containing about 53 tabs. 
then you close canary with the chrome->exit option. 
then you restart canary and it doesn't restore all your icons. 
then you close canary again (with the chrome->exit option?)
then you restart canary again and all your icons appear ok.

is that a good summary?
can i assume that before closing canary the first time you have some suspended tabs.
and then when you restart, those suspended tabs don't show the proper icons.
and finally on the next restart, you _still_ have those suspended tabs but they show the correct icons?

**Comment by liv-in-sky** [comment] 2018-10-05 12:13
I think your assuming is right

what I did yesterday 
- update to canary 64 bit - > icons not working
- deinstalled suspender on chrome and canary (because of the sync?!)
- installing again - > icons not working (even more worse - icons aren't shown after restart canary)
- loaded all tabs and disabled suspender 
- saved tabs and closed a lot of them 
- restarted and enabled suspender


today morning everthing worked fine - all  icons are shown. I have 3 windows with 60 tabs. My estimation is that closing the tabs and the start with "cleaned" tabs was the solution - I will see what the weekend will bring

in any case  - thanx for your time

**Comment by liv-in-sky** [comment] 2018-10-05 14:38
me again - this was happened about 5 minutes ago

canary asked for an update - I have done  this - then I have to restart canary - after the restart 50% of icons are missing.
solution: I have to unsuspend all tabs and this FOR EACH WINDOW !  then it is working again

**Comment by deanoemcke** [comment] 2018-10-06 03:16
@liv-in-sky when you click on a tab with a missing icon, does the icon fix itself?

**Comment by liv-in-sky** [comment] 2018-10-06 07:50
yes

**Comment by deanoemcke** [comment] 2018-10-11 22:06
I have been able to recreate this consistently on the new version by closing a window containing suspended tabs, and then using the 'reopen closed tab' option, which will restore the whole closed window. When this happens, some of the suspended tabs will not reload the correct favicons and titles.
I'm working on a fix for this now.

**Comment by deanoemcke** [comment] 2018-10-11 22:10
Fix for the above (68f42da)

**Comment by liv-in-sky** [comment] 2018-10-12 16:13
hi - good to know that it is  not only my setting. I think it will be automatically updated or do I have to install something ?

thanx a lot - armin

**Comment by deanoemcke** [comment] 2018-10-13 04:10
@liv-in-sky you will be updated automatically, although that might be a week away.

**Comment by deanoemcke** [comment] 2018-10-14 18:57
I have made another optimistic fix for this issue (v7.0.133)

**Comment by deanoemcke** [comment] 2018-10-14 18:59
And here is a nice video demonstrating the issue. Care of @CollinChaffin over in issue #784.
Thanks Collin :)

![image](https://user-images.githubusercontent.com/1051763/46920809-a5acc080-cfc1-11e8-8e10-2c9915e7ccb5.png)

**Comment by fwextensions** [comment] 2018-10-15 04:56
@mkz7 I built a tab-switching Chrome extension called [QuicKey](https://chrome.google.com/webstore/detail/quickey-%E2%80%93-the-quick-tab-s/ldlghkoiihaelfnggonhjnfiabmaficg) that has special handling for tabs suspended by The Great Suspender.  It doesn't have the session management features of Tabli, but it does make it easy to type a few characters to find a tab by its title or URL, or to navigate between recently used tabs.  It renders suspended tabs differently its menu, lets you switch to one and unsuspend it with a keyboard shortcut, and it displays the correct title and favicon even if the tab just shows "Suspended Tab".

**Comment by liv-in-sky** [comment] 2018-10-15 08:03
I can confirm the "tabli" issue - all chrome tabs have the right icons - in tabli they have the "suspender"-icons - I'm using another extension called "splitup" - everything is fine there (second picture)
![tabli](https://user-images.githubusercontent.com/18462890/46937396-7baadb00-d061-11e8-8719-06159d2d9370.png)
![split](https://user-images.githubusercontent.com/18462890/46937398-7baadb00-d061-11e8-9cdc-b33c580e5922.png)

**Comment by deanoemcke** [comment] 2018-10-16 04:05
@mkz7 I looked into Tabli. The issue is to do with how their extension is obtaining the favicon to display in their list. If they were to query the chrome tabs api, they would be able to get the correct favicon, but they don't do this. 

Just to keep things on topic, these last few posts should probably be discussed in a new thread as they're not specifically related to this issue. 
This issue is for the favicon and/or title of actual suspended tabs. Not for a representation of those tabs elsewhere.

There is a related issue for missing favicon/titles on chrome synced devices: https://github.com/deanoemcke/thegreatsuspender/issues/46
And potentially this issue for missing favicon/titles in chrome://history: https://github.com/deanoemcke/thegreatsuspender/issues/717

**Comment by CollinChaffin** [comment] 2018-10-16 04:30
Commit 369cc38 today has gotten 100% worse and does the opposite of fixing this issue that I and others are having with suspended tabs being manipulated via other tools and not having the favicon.  I just updated to test and was really shocked to see that if I issue a single TGS command to simply suspend all tabs in the current window, EVERY SINGLE tab suspends with the blockhead icon - no favicon whatsoever.  This issue seems to be getting worse and worse I have not diffed the code from a few months ago and I realize a ton of other refactoring is much of the cause of these changes, but bear in mind this whole ongoing favicon refresh issue did not even exist a couple months ago at all and my tabs stored in any other session manager suspended were stored with the proper icon, as well as a live suspend of all tabs changed their favicons properly upon suspend, so perhaps we need to revisit that codebase.

**Comment by CollinChaffin** [comment] 2018-10-17 20:39
UPDATE: I can confirm this DOES in fact now revolve around the code related to the `Apply Chrome's built-in memory-saving when suspending` option as shown here in video.  Note how the issue completely disappears and the favicon is shown correctly in the very same session when I simply disable that new feature and re-run the manual suspension.  Note this also occurs with auto suspension.  Hopefully this helps you to track down the issue.

DEMO:

![snag-10-17-20183 15 06 pm avi](https://user-images.githubusercontent.com/9301483/47114826-63e37a80-d24c-11e8-9738-43274e06937b.gif)

**Comment by mkz7** [comment] 2018-11-03 21:17
> UPDATE: I can confirm this DOES in fact now revolve around the code related to the `Apply Chrome's built-in memory-saving when suspending` option as shown here in video. Note how the issue completely disappears and the favicon is shown correctly in the very same session when I simply disable that new feature and re-run the manual suspension. Note this also occurs with auto suspension. Hopefully this helps you to track down the issue.
> 
> DEMO:
> 
> ![snag-10-17-20183 15 06 pm avi](https://user-images.githubusercontent.com/9301483/47114826-63e37a80-d24c-11e8-9738-43274e06937b.gif)

The option mentioned in the above 'fix' -- i.e., to uncheck "Apply Chrome's built-in memory saving when suspending" -- isn't displayed on my TGS Settings page. 

'Where to' to find it?

**Comment by fwextensions** [comment] 2018-11-06 02:38
@mkz7 which version of the extension do you have installed?  If you right-click the TGS icon and select Options, and then go to About, the version number is at the top.

**Comment by CollinChaffin** [comment] 2018-11-18 14:08
This is still not fixed as of commit e2d748c dated 11/14 even normal suspend operations are resulting in the blockhead generic favicon when that new switch for native discard is enabled.

**Comment by deanoemcke** [comment] 2018-11-19 10:56
@CollinChaffin can you try the latest commit (v7.0.144)?
I have made some more changes around favicon handling and fixed at least one outstanding bug in this code.

**Comment by mkz7** [comment] 2018-11-21 11:57
> _@mkz7 which version of the extension do you have installed? If you right-click the TGS icon and select Options, and then go to About, the version number is at the top._

[Re: I don't see "Apply Chrome's built-in memory saving when suspending."]

Thanks. I'm using v7.0.109 (on a Mac). (Don't versions update automatically?)

**Comment by mkz7** [comment] 2018-11-21 22:52
> _@mkz7 I looked into Tabli. The issue is to do with how their extension is obtaining the favicon to display in their list. If they were to query the chrome tabs api, they would be able to get the correct favicon, but they don't do this._

@deanoemcke  Just received this from the developer (Tabli):

"Tabli ❤️ The Great Suspender. A number of Tabli users also use The Great Suspender, an excellent Chrome extension that automatically suspends tabs you aren't using, freeing memory and CPU. **This release of Tabli resolves a long-standing issue to ensure the correct icon and URL are shown for tabs suspended by the Great Suspender, and adds a little 💤 icon to indicate suspended tabs.**"

**Comment by deanoemcke** [comment] 2018-11-25 22:14
@mkz7 Versions do update automatically, except that I'm doing a staggered rollout of newer versions so not everyone will get it at the same time.
That said, v7.109 IS the latest chrome webstore version. But it has known favicon issues. It also does NOT have the new "Apply Chrome's built-in memory saving when suspending." option. That is still in development and will be released shortly.
The latest development version of the extension should also have resolved all outstanding favicon issues (v7.0.147).

And awesome news from Tabli! Thanks for posting here.

**Comment by CollinChaffin** [comment] 2018-11-27 13:49
Sorry @deanoemcke I replied on other issue but not here to confirm that as of latest commit things were looking much better and looked to be resolved (as far as this issue).  However, I see that just yesterday you committed what looks like some more significant improvements so let me re-test quickly here and I will return and edit this post to confirm still fixed.

**Comment by danilaml** [comment] 2018-12-18 16:58
Recently I've also started to experience this issue, however I'm on the latest stable version so I cannot confirm whether it was fixed in master or now. Perhaps an update is an order.

**Closed** 2019-02-06 04:02 UTC
Labels: bug-confirmed, waiting-on-release

**Comment by guilleortas** [comment] 2022-08-17 18:30
This is still an issue currently. I'm on Brave v1.42.97 Chromium: 104.0.5112.102 (official build) (64 bits)

**Comment by chaoscreater** [comment] 2024-02-25 14:20
Still an issue on 7.1.12 on Thorium browser. Not using **Apply Chrome's built-in memory-saving when suspending** and the favicon is still being set to the extension's icon when suspending a tab.
