### ISSUE TITLE
Request: Don't Suspend Tabs Whilst Casting

### ISSUE THREAD

**Issue by ghost** [deanoemcke/thegreatsuspender#451] opened 2016-11-08 19:44 UTC
Great suspender will suspend tabs whilst casting content. Please make it so it doesn't do this.

**Comment by deanoemcke** [comment] 2018-04-17 04:59
Will need to do some testing on this.

**Comment by deanoemcke** [comment] 2019-03-16 08:08
Duplicate of #378

**Closed by deanoemcke** 2019-03-16 08:08 UTC
Labels: blocked, feature
