### ISSUE TITLE
Crashing Chrome Dev channel when resuming tabs

### ISSUE THREAD

**Issue by geeknik** [deanoemcke/thegreatsuspender#29] opened 2013-03-04 17:50 UTC
I was using the latest version of this extension with Chrome 27.0.1425.2 dev-m (running on 64-bit Windows 8) and when I would unsuspend tabs, Chrome would crash. After removing this extension, the crashes stopped. Not sure if it was conflicting with another extension or was just the dev version hating on your extension.

**Comment by deanoemcke** [comment] 2015-01-13 11:32
I'm treating this as a duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/23.
For all bug reports of this extension causing chrome to crash please add to this other isssue.
Closing.

**Closed by deanoemcke** 2015-01-13 11:32 UTC
