### ISSUE TITLE
Add a keyboard shortcut for "Don't suspend for now

### ISSUE THREAD

**Issue by isMyUsername** [deanoemcke/thegreatsuspender#212] opened 2015-05-22 18:01 UTC
That way, I don't have to do it via the menu and I can just click a macro to prevent suspension of an important tab like I can do for Suspend Active Tab

**Comment by kankaristo** [comment] 2018-03-17 17:33
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/208?

And according to that issue, it's implemented and coming in the next release.

**Closed** 2018-04-17 05:58 UTC
Labels: duplicate
