### ISSUE TITLE
Feature Request: Option to not suspend Tab which is playing audio

### ISSUE THREAD

**Issue by PCMRStudio** [deanoemcke/thegreatsuspender#235] opened 2015-06-12 16:28 UTC
To lazy to code it and make a merge request :palm_tree:

**Comment by DanAtkinson** [comment] 2015-06-18 11:15
:+1: This is definitely a good feature to add.

**Comment by DanAtkinson** [comment] 2015-06-18 14:21
At the very least, this issue is blocked by a Chromium feature request - [Add extension API and events to determine which tabs are playing audio](https://code.google.com/p/chromium/issues/detail?id=438903).

Until that lands in Chrome stable, it won't be possible to implement this functionality.

**Comment by rubensainiuc** [comment] 2015-07-02 10:43
I would also like this feature to exist, after Chrome allows it.
:+1:

**Comment by deanoemcke** [comment] 2015-07-03 04:38
Closed as duplicate of issue #28

**Closed by deanoemcke** 2015-07-03 04:38 UTC
