### ISSUE TITLE
Chrome: "This extension may have been corrupted"

### ISSUE THREAD

**Issue by jmahhh** [deanoemcke/thegreatsuspender#422] opened 2016-07-29 01:13 UTC
According to my Extensions. The product's been disabled in the Chrome store as well. What's going on?

**Comment by mylemans** [comment] 2016-08-04 15:20
@jmahhh Not for me

https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?utm_source=chrome-app-launcher-info-dialog

**Comment by deanoemcke** [comment] 2017-07-25 15:50
Possible duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/551

**Closed by deanoemcke** 2017-07-25 15:50 UTC
