### ISSUE TITLE
Suspended tabs show blockhead favicon on restart

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#719] opened 2018-08-21 03:08 UTC
Sometimes when restarting chrome after a crash or by 'continuing where i left off' some of the restored tabs that were suspended before previous shutdown will not load the proper 'faded' favicon.
Instead they will show the extension blockhead icon. Once these tabs are clicked, they will update to the correct favicon.

![image](https://user-images.githubusercontent.com/1051763/44378138-f3c7ab00-a4cd-11e8-83db-9b87c5f691f1.png)

I think the problem has something to do with how chrome prioritises tab reloads on chrome restart. It seems to stagger the reloading of non-focused tabs trying to get the focussed tab fully functional first. It seems that for some of these background tabs, it never allows the javascript on the suspended page to run - this is what updates the favicon and page title.
But when you give one of these tabs focus, it then runs the page load javascript, and the favicon and title update as expected.

This bug happens very infrequently for me and is very hard to reproduce.

**Comment by fwextensions** [comment] 2018-08-22 19:57
Still happens for me on my old Win7 laptop with 8GB RAM and a few hundred tabs open across ~20 windows.  Much less common on a newer machine. Perhaps it's the large number of windows part that is making it more common for me. 

![image](https://user-images.githubusercontent.com/61631/44487239-a0a74280-a60a-11e8-856f-1f3868557699.png)

At least the tab title is correct with the 7.x branch, which wasn't always true with 6.30.

**Comment by fwextensions** [comment] 2018-08-23 00:06
Yes, they stay that way throughout the session, and most after a restart as well.  However, as soon as they're focused, the favicon does update.  

The tabs in the screenshot were suspended with 7.0.72.  I've been meaning to try the latest build on my personal laptop with 16GB RAM.  I think it's a combination of lots of tabs, lots of windows, and lots of memory pressure. 

All the tabs with the default icon seem to be in the discarded state, so that explains why they update when focused.  This is different than 6.30, when the background page sometimes wouldn't be available and the title was just "Suspended Tab".  

Actually, I wonder if tab discarding explains the suspended tabs with default icons.  In other words, lots of tabs are suspended *and* then get discarded because of low memory.  On relaunch, Chrome leaves the `suspended.html` tabs discarded, and assumes the TGS icon is the right one, since it *is* a TGS page.  Then, because there are a lot of tabs and a lot of open windows with active tabs showing heavy pages (GDocs, etc.) and not enough memory, Chrome doesn't bother undiscarding those suspended pages.  So the page is never loaded, the extension is never notified, and it never gets a chance to update the icon.

I supposed a workaround would be for TGS to check for discarded tabs sometime after launch, check each if it's `suspended.html` and its favicon is the TGS icon, then update the icon to the correct one.

**Comment by deanoemcke** [comment] 2018-08-23 00:27
The fact that the favicon updates when it gains focus definitely confirms it's an issue with the javascript on the suspended tab not being run in the background. But is allowed to run once it gains focus. Although it's interesting that the title does update as this is also set via the same javascript. Perhaps the title is cached somehow.

Your theory about discarded tabs sounds mostly correct. I don't think that the discarded state of a tab before chrome is closed carries over to a restart, although it is highly likely that when restarting chrome under heavy memory pressure, some tabs are discarded before they have a chance to load. 

On a related note, the latest version has a new feature which detects tab discarding, and instead suspends the tab. Although perhaps during startup, the discarding is happening before the extension has a chance to load and run the detection code.

Your idea about checking for discarded tabs after launch is a good lead. I'll have a play around and see what I can do. Although first I'll need to be able to reliably reproduce the issue :/ 
Perhaps a virtual machine with low memory will work.

**Comment by fwextensions** [comment] 2018-08-27 23:34
Just happened with version 109 installed from GitHub:

![image](https://user-images.githubusercontent.com/61631/44691072-fec09500-aa11-11e8-801a-bf129a90428d.png)

I'd set 109 to never suspend, but I guess the "suspend instantly when memory is low" option was set by default, and at some point I noticed it going through discarded tabs and suspending them.  So I turned off that feature.

About an hour ago, I had to restart the OS and Chrome.  I don't think I noticed the blockheads at first, because they didn't appear in the couple of windows I was using most.  But just now, I noticed lots of tabs with correct titles but the faded out blockhead icon.  

I have 361 tabs open, 277 of which are discarded, and 211 of those are pages suspended by v109.  Win7, Chrome 68.

I pasted the log from v109 here, with URLs removed (it would probably be good to not print URLs to the console to make it easier for testers to share logs): https://gist.github.com/fwextensions/cf35acf781058a3fe24e52b3a20af2b9

I launched Chrome at 2:55pm, so it looks like it's missing the first 10 minutes after startup.  One thing to notice is that it's setting a `tabFlag` on tab 1063 ~45 times in a row, and then getting 45 responses.  This happens with some other tabs, like 921 (which happens to be this tab, strangely).  

1063 is a tab that has an Enterprise Gdoc open, which I think we determined was blocking content scripts from being injected.  So maybe that's causing the looping?  (Though it's strange that it's getting a response if there was no script to respond, or perhaps it's in a weird state.)

**Comment by deanoemcke** [comment] 2018-08-31 17:56
I have managed to recreate this issue (by discarded on tabs on extension start) before doing the extension initialisation. I have committed some new code to force any suspended tabs that get discarded during startup to undiscard themselves. Hopefully this doesn't cause any performance issues (given that the tabs are only being discarded due to low memory).

Thanks for all your help with this one @fwextensions

**Comment by deanoemcke** [comment] 2018-09-02 01:37
@fwextensions my experience with copy/pasting in the logs is that the objects get properly serialized when you paste them into a text document. who knows why this does not happen with you.

as for the favicons. the favicon defined in suspended.html is the blockhead icon. therefore, when chrome navigates to that url, it will always show this icon first. it has nothing to do with whether the 'proper' favicon for the original site exists or is transparent etc.

as you pointed out, the swapping of the blockhead favicon for the 'proper' one happens in the javascript. if the tab is discarded before this javascript can run, then the favicon never gets updated. 

the real problem is, once a tab is discarded, it is completely unreachable. it will not accept message requests. it does not even get returned with `chrome.extension.getViews()` which is supposed to return every open tab owned by the extension (which should be all suspended tabs).

the only way i can see to run that javascript is by reloading the tab (which is actually just the equivalent of suspending it, so it's not that bad).

also, this code is only run during extension initialisation. and it runs in such a way that the checking for discarded suspended tabs is staggered. so the tab will stay discarded for a few seconds at least, giving chrome it's wish of freeing up system resources when it needs them.

the one caveat to this however, is that you may still encounter the blockhead favicon issue if restoring a lot of suspended tabs outside of chrome restart. ie: restoring a lot of suspended tabs via a session manager.

**Comment by fwextensions** [comment] 2018-12-14 07:56
Probably this isn't super helpful, since it's an old build, but I'd been running the 110 build from GitHub for awhile with no issues.  IT just rebooted my Windows 10 laptop and after I logged in, Chrome eventually auto-started (maybe 30 seconds after login) and restored the previous session of about 240 tabs and 7 windows.  All the suspended tabs showed blockhead favicons and didn't update on their own.

![image](https://user-images.githubusercontent.com/61631/49990293-fa24db80-ff31-11e8-8406-e1743afd1ac5.png)

All the titles are fine and focusing the tab does fix up the favicon.  It looks like maybe a few of the favicons updated after the auto-restart, but the vast majority didn't.  I'd previously quit and restarted Chrome, and the favicons had updated in the background.  What was different in this case was the forced restart, then login and auto-start of Chrome while other apps were also restarting.

Chrome Version 71.0.3578.98 (Official Build) (64-bit), Win 10 Enterprise, v1703, 16GB RAM

**Comment by fwextensions** [comment] 2018-12-15 01:41
I haven't restarted since the above, and now I'm noticing that tabs are getting suspended into a bad state, where it's just showing a blank suspended.html page, with the title just the URL.  The console has `"Could not establish connection. Receiving end does not exist."` errors, looks like one for each suspended tab.

However, I just realized I'd pulled from upstream master, but didn't reload the extension, which is loaded from the unpacked `/src` folder.  I'd assumed Chrome had already cached those for the extension, but maybe it's pulling in those new source files, which must be incompatible with what's in memory.  

I refreshed the extension, and then remembered why I hadn't before: all the suspended tabs closed, which was a little terrifying.  But v155 did recover all the tabs (I think) and all the blockhead icons were updated.  So hopefully it won't happen again with this version.

**Comment by deanoemcke** [comment] 2018-12-18 10:19
@fwextensions Thanks a lot for your report. Sorry about the scare, but thanks to your detailed account, I can confirm that it was indeed due to pulling master without restarting the extension.
the latest version (7.0.155) has done away with the `suspended.js` file completely, which is what all the older versions relied on to load the suspended tab.

i'm assuming that what happened to you will not happen to production users, given that an extension restart is forced when the code updates.

let me know if you encounter any more favicon issues. and i'm glad your tabs recovered correctly! you should also have a saved session that accompanies any new version update.

**Comment by samboa86** [comment] 2018-12-27 16:55
I also have this issue was going to report but saw it was already posted. I have to focus on the tab (I hold down ctrl+tab and scroll thru all of them)

**Comment by fwextensions** [comment] 2019-01-04 20:14
I haven't noticed any blockhead issues since 155.  The only other issue was the wrong Gdocs icons, which is fixed in 159.

**Comment by deanoemcke** [comment] 2019-01-26 11:12
@samboa86 can you please let me know the version of the extension you were using when you encountered the blockhead icon? and do you still have the same issue on the latest development version here on gitHub?

**Closed** 2019-02-06 04:05 UTC
Labels: bug-confirmed, prioritised, waiting-on-release

**Comment by inside83** [comment] 2019-05-09 02:28
I'm on version 6.30, Chrome 73.0.3683.103, Win 10 with 16 GB of RAM.
Getting blockhead icon instead of favicon after restart AND during normal use (without restart).

**Comment by fwextensions** [comment] 2019-05-23 23:16
@deanoemcke I finally pulled the latest version (7.1.4) last week and have been running that.  After a restart with ~450 tabs (probably 3/4 suspended) and 10 windows, almost all the icons updated.  I did notice a line of maybe 10 in a row that still had the blockhead after all the other tabs updated.  I didn't get a chance to report it then, but now a couple days later, I don't see the blockheads anymore.  So it seems like they fixed themselves at some point.  The icon handling seems pretty buttoned-up at this point.  👍 

@inside83 That's a known bug in 6.30 which seems to have been fixed in the latest (unreleased) versions.

**Comment by inside83** [comment] 2019-05-24 00:53
Yeah, thank you for the reply.
I installed v7.1.0 and it's beyond great.
I'm just wondering why is not released yet.

**Comment by fwextensions** [comment] 2019-05-24 01:15
Updating TGS is tricky, because Chrome will close all of the suspended tabs when it updates, and then the extension has to reopen them all, so there's a potential for losing tabs.  I think it's already rolled out to a bucket of users.

**Comment by HamRusTal** [comment] 2019-07-10 20:28
This issue reproduces consistently for me in a 32-bit Chrome restoring 30 tabs on its startup (after a clean exit). Around 12 tabs are from white-listed sites and load normally, some of them quite heavy on memory. Other tabs expose TGS icon however long I wait.
Chrome 75.0 (32-bit, official build), TGS 7.1.0 (from Chrome Web Store).
In which TGS version is the issue fixed?
