### ISSUE TITLE
Option to keep fav icon when suspended

### ISSUE THREAD

**Issue by atollis** [deanoemcke/thegreatsuspender#911] opened 2019-04-06 02:41 UTC
Currently when a tab is suspended it shows the suspender icon but id like an option to retain the sites icon and if possible change the opacity or apply a color overlay to the icon.

**Comment by Jollfye** [comment] 2019-04-06 10:20
hmm looks like u r using old TGS extension version, I would recommend u to update as I wrote bout possibly the same situation [here](https://github.com/deanoemcke/thegreatsuspender/issues/905#issuecomment-476802818).

**Comment by deanoemcke** [comment] 2019-04-08 11:11
This has been fixed in the latest version.

**Comment by deanoemcke** [comment] 2019-04-08 11:11
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/719

**Closed by deanoemcke** 2019-04-08 11:11 UTC
