### ISSUE TITLE
Enhancement: Do not suspend the last N used tabs

### ISSUE THREAD

**Issue by dumblob** [deanoemcke/thegreatsuspender#471] opened 2017-02-16 11:27 UTC
Based on my experience with using of The Great Suspender, it would make sense to **not** suspend `N` last used tabs. The `N` would be user-settable number (from `0` to `Number.MAX_SAFE_INTEGER`) and would not take into account whitelisted tabs (nor pinned tabs in case the user selected the "Do not suspend pinned tabs" option).

The backround idea is, that one uses few tabs more than others and thus does not want to wait for loading of those few and will rather sacrifice some memory for them.

**Comment by cschneiker** [comment] 2017-03-06 22:32
This would be especially useful when opening up a batch of bookmarked tech news related tabs, and links therein. This would also be especially useful when doing initial broad research on some topic, which also temporarily produces lots of new tabs.

Given sessions that already have 100+ tabs or more, I'd like to keep the default suspend time fairly brief (so that Chrome becomes usable within that period of time after restarts). However, I'd also like to keep the most recent few dozen new tabs opened for at least an hour or two while working through them.

The proposed enhancement would be extremely useful for such purposes.

**Comment by OmgImAlexis** [comment] 2017-03-16 03:45
This would be amazing as I pin all my frequently used tabs but still want to keep 2 - 3 tabs without them suspending. I'd like everything else to suspend after 10 minutes though.

**Comment by dumblob** [comment] 2017-06-14 21:23
@deanoemcke what do you think about this proposal? I know you're quite busy also with The Great Discarder, but still I dare to ask for your attitude to implementing this functionality which from my point of view is quite a break-through when it comes to user experience and also data usage in case one is connected through a mobile connection (which is often my case, I admit).

**Comment by deanoemcke** [comment] 2017-06-15 13:40
I think this is a great idea. It's something I would like to implement, but it is quite a significant departure code-wise from how the extension is currently implemented (ie. it's quite a bit of work).
I'm going to close this issue, and it is a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/136

**Closed by deanoemcke** 2017-06-15 13:40 UTC
