### ISSUE TITLE
Google https Pages not Whitelist ing

### ISSUE THREAD

**Issue by emagin** [deanoemcke/thegreatsuspender#76] opened 2014-02-04 22:15 UTC
I am on Google pages constantly (gmail, contacts, drive) and when I whitelist these they don't seem to take.
Here is an example of my whitelist
These pages keep getting suspended.

mail.google.com/mail drive.google.com
www.google.com/calendar play.google.com/music/listen mail.google.com drive.google.com

**Comment by deanoemcke** [comment] 2015-01-22 12:20
Possible duplicate of issue #60. Closing this issue as I believe all whitelisting issue have been resolved. These fixes will be pushed to the chrome webstore shortly.

**Closed by deanoemcke** 2015-01-22 12:20 UTC
