### ISSUE TITLE
IDEA: Global Toggle for Suspension

### ISSUE THREAD

**Issue by osiixy** [deanoemcke/thegreatsuspender#698] opened 2018-07-13 17:39 UTC
### IDEA
If I may suggest an idea
it could be a global toggle
for suspension in quick menu
which would make it possible
to pause every suspension
till further action.

**Comment by liamjohnston** [comment] 2018-08-06 20:35
As a workaround, you can head to the settings page and change the automatically suspend' dropdown option to 'never'

**Comment by deanoemcke** [comment] 2018-08-15 04:45
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/256

**Closed by deanoemcke** 2018-08-15 04:45 UTC
