### ISSUE TITLE
Bug :-" Not showing Title of suspended window after restarting chrome"

### ISSUE THREAD

**Issue by Aabhi021290** [deanoemcke/thegreatsuspender#173] opened 2015-04-04 10:35 UTC
Bug:- Lets say I suspended some tabs in  Chrome browser. Now I close Chrome windows. Now when I start chrome browser again, I am not able to distinguish between the suspended tabs because they are not showing any titles or website link of suspended tabs.I am attaching 2 screen shots.
First is OK (before I close browser)
Second not showing title.(after starting closed browser)

I am using Chrome 41.0.2272.118 m , Windows 8 32 bit
Please fix this.

Thank you  for your amazing extension :)
![suspended tab 1 ok](https://cloud.githubusercontent.com/assets/11795895/6992300/465ac134-dae4-11e4-8a53-5829207624cf.png)
![suspended tab 2 bug](https://cloud.githubusercontent.com/assets/11795895/6992301/4f857dc6-dae4-11e4-958a-213d43d73787.png)

**Comment by deanoemcke** [comment] 2015-04-05 21:18
Could you tell me the version of The Great Suspender? You can check from the chrome://extensions tab.
Also, I assume that for the 'On Startup' option you have the option to 'Continue where you left off' option set? I am unable to recreate this issue on my computer which is why I'm trying to get more info.

**Comment by Aabhi021290** [comment] 2015-04-06 20:07
I am using tab suspender 6.14
Yes you are correct . I  set " Continue where you left option"
Also Sometime this problem occur, sometimes not
Also I noted when I reload that buggy suspended tab (not unsuspending simply reloading by right click options) ,problem automatically solves. 
Sorry for bad english.  :)

**Comment by wizonesolutions** [comment] 2015-07-25 15:59
I'm also using 6.14, and I see the same behavior. Instead of showing the tab title, it just shows Suspended Tab.

Screenshot
https://www.evernote.com/l/AAI9-WvRXLlJ6YbdK4DA1SnfHocj78l0EY0

**Comment by lugoazul** [comment] 2016-04-24 13:40
Hello. I'm having this issue as well on v6.21.
The back button workaround solves the problem though. 

Thanks for this extension!

Opera: 36.0.2130.65
System: Mac OS X 10.7.5 32-bit

**Comment by deanoemcke** [comment] 2017-07-25 18:06
Can anyone confirm if this is still an issue in the latest release (v6.30)?
Thanks.

**Comment by deanoemcke** [comment] 2018-08-21 03:12
This is most likely a duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/719.
However this one relates to an older version of the extension where the icon just wasn't able to load at all.

**Closed by deanoemcke** 2018-08-21 03:12 UTC
Labels: bug-unconfirmed, prioritised
