### ISSUE TITLE
Unable to suspend tabs manually

### ISSUE THREAD

**Issue by thecrazy** [deanoemcke/thegreatsuspender#285] opened 2015-09-04 17:34 UTC
Clicking suspend this tab or suspend other tabs does nothing for me. Used to work with older versions, not sure if it ever worked since you made a major revamp.

**Comment by DSelitskiy** [comment] 2015-11-11 01:14
For me, doing manual suspend always suspends the most recent/last opened tab instead of the active one. Could be related.

**Comment by deanoemcke** [comment] 2015-11-11 04:36
Can you guys tell me which version of the extension you are on? Unable to replicate this issue on my computer.
Also, how are you triggering the manual suspend. Via the popup menu or keyboard shortcut?

**Comment by DSelitskiy** [comment] 2015-11-11 04:40
Popup menu. v6.14

**Comment by codisms** [comment] 2016-05-27 16:10
I'm having the same issue.  v6.14.  It might be that I'm trying to suspend a tab that is a whitelisted domain.

**Comment by deanoemcke** [comment] 2017-07-19 02:11
Could somebody please confirm if this is still happening in the latest release (v6.30) ?

**Comment by deanoemcke** [comment] 2018-08-21 02:55
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/574

**Closed by deanoemcke** 2018-08-21 02:55 UTC
Labels: bug-unconfirmed, caused-by-old-version-of-extension?, prioritised
