### ISSUE TITLE
Feature request: Add option to suspend all tabs when closing the entire browser

### ISSUE THREAD

**Issue by thecrazy** [deanoemcke/thegreatsuspender#286] opened 2015-09-04 17:35 UTC
The idea is that reopening a browser with a lot of tabs will be faster.

Thanks for the great extension.

**Comment by deanoemcke** [comment] 2015-09-26 06:08
Duplicate of issue #157.
Also see issue #49 for a feature request to start all tabs as suspended on startup (regardless of whether they were suspended on close).

**Closed by deanoemcke** 2015-09-26 06:08 UTC
