### ISSUE TITLE
Change suspended tab title 

### ISSUE THREAD

**Issue by arieljannai** [deanoemcke/thegreatsuspender#320] opened 2015-11-03 08:32 UTC
Hi,

The html title set to suspended tabs is "Suspended Tab".
When the tabs are being synced (with chrome for example) it shows me a lost of suspended tabs, and I cannot know which is which.
If you can add the real title after suspended tab it would be much comfortable. (such as "Suspended Tab - ExplosmEntertainment - YouTube", or "Suspended Tab - Facebook" etc.)

Thanks,
Ariel.

![image](https://cloud.githubusercontent.com/assets/3811594/10903791/1f51c25c-8216-11e5-8151-1cf27db1e79a.png)

**Comment by deanoemcke** [comment] 2015-11-04 06:53
Duplicate of #225

**Closed by deanoemcke** 2015-11-04 06:53 UTC
