### ISSUE TITLE
Text invisible on suspended tabs

### ISSUE THREAD

**Issue by FatCat0** [deanoemcke/thegreatsuspender#474] opened 2017-02-20 16:14 UTC
A lot of my suspended tabs are covered with invisible text. These appear to be about the right length, but mousing over and even highlighting don't allow me to read the text.

![image](https://cloud.githubusercontent.com/assets/16107668/23133044/ac163638-f75d-11e6-91c5-079b1354a942.png)

**Comment by deanoemcke** [comment] 2017-07-25 18:34
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/366
Are you still having this issue on the latest version? (v6.30)

**Comment by FatCat0** [comment] 2017-07-25 18:41
Thanks for the followup. I have not noticed it but will let you know if
ever I do see it again.

**Closed** 2017-07-25 19:07 UTC
Labels: caused-by-old-version-of-extension?, duplicate, prioritised
