### ISSUE TITLE
Whitelisting PDFs or by file type

### ISSUE THREAD

**Issue by jddcef** [deanoemcke/thegreatsuspender#435] opened 2016-09-02 20:31 UTC
I would like to be able to tell the extension to not suspend PDF's (or any such file types), as they are usually large and redownloading them would be a waste.  

Thanks.

**Comment by mooreaa** [comment] 2016-09-18 10:33
I agree. I also found it suspending jpg/png files and it seems counter intuitive to suspend pages that are fixed assets as it should not be in active memory anyway.

**Comment by D0nvt** [comment] 2016-11-29 16:45
I found I was able to whitelist pdfs by just adding ".pdf" to the whitelist instead of using a regular expression such as "*.pdf" - I've attached a screenshot as an example.
However, I was unable to get regular expressions working in general. This is likely a separate issue (or rule input error), but even putting the example regular expression [/^https:.*google\.com/] that displays when hovering over the "?" of the whitelist, I don't see any pages whitelisted as a result.


![screenshot 2016-11-29 at 11 38 59](https://cloud.githubusercontent.com/assets/7391074/20719190/32f3fbc0-b629-11e6-8399-43090088791c.png)

**Comment by deanoemcke** [comment] 2017-06-09 04:35
@D0nvt possibly a silly question but, are you actually including the square brackets in the whitelist with your example of `[/^https:.*google.com/]` ?
This would cause it to fail as the correct form should be `/^https:.*google.com/`

I have just retested the whitelist for regular expressions and everything seems to work ok?

**Comment by D0nvt** [comment] 2017-06-11 13:00
@deanoemcke it's possible I was - I haven't fiddled with these setting since around that last post though, and all I ended up leaving was .pdf. In any event, can confirm regexp whitelisting works as given, thanks!

**Comment by deanoemcke** [comment] 2017-07-25 19:30
I'm not sure I agree that it doesn't make sense to suspend pdf tabs. From some testing, a pdf can take up a significant amount of memory. Suspending these tabs will free that memory.

I think i'd rather just leave this to be handled by a whitelist regex.

**Comment by mindsocket** [comment] 2017-12-11 02:39
I encountered a slightly different use case in support of this issue being resolved.
I had a PDF file with form inputs (different to HTML forms so the setting to leave such things alone didn't kick in), and suspending the tab blew away what had been typed in.

**Comment by deanoemcke** [comment] 2018-02-06 18:03
@mindsocket i think this would be better addressed in a separate issue. something like 'form input not detecting pdf edits'.

i am still not convinced that it is worth having something specific in the extension to handle pdfs.
the usecase of editing a pdf is chrome is fairly uncommon i would say.

**Comment by deanoemcke** [comment] 2019-02-28 20:58
duplicate of: #257
will not fix as whitelisting provides an adequate workaround

**Closed by deanoemcke** 2019-02-28 20:58 UTC
Labels: feature
