### ISSUE TITLE
Dark theme on last tab gets lost after browser restart

### ISSUE THREAD

**Issue by codemedic** [deanoemcke/thegreatsuspender#905] opened 2019-03-26 10:07 UTC
I cannot place exactly what is going one, but here is what I think is happening.

I have configured the TheGreatSuspender to use its dark theme. When the timer expires, a tab does get suspended with the dark theme, but once the browser restarts, the last tab always seem to loose the dark theme. It also loosed the text describing what it has suspended. Please see screenshot below.

During restart, the faded tab icons also seem to get lost; being replaced by TheGreatSuspender icon, which makes it harder to figure out which tab is what. Tabli extension does help with this to an extend, but it will be nice if TheGreatSuspender can do it by itself.

PS: To all contributors; Thanks for the effort on this extension, much appreciated!

 * Extension version: 6.30
 * Browser name & version: Google Chrome 73.0.3683.86 (Official Build) (64-bit)
 * Operating system & version: Ubuntu Linux v16.04.6 LTS

![image](https://user-images.githubusercontent.com/691011/54988722-f849ca00-4fae-11e9-91f3-cf61bdbfe00c.png)

**Comment by Jollfye** [comment] 2019-03-26 19:06
@codemedic, as not a developer of TGS I would suggest u to look for some external session manager extension here #742 to backup ur current tabs and session then update ur The Great Suspender extension to latest Chrome Web Store release version 7.1.0 dated March 17, 2019, restore ur session from backup (if somehow it was lost during update) and report here whether u still have any of described by u issues or not to help dev to fix them. A lot was already fixed since 6.30, soo update.

**Comment by deanoemcke** [comment] 2019-03-27 08:20
I can confirm that all of these issues will be resolved by updating to the latest webstore version.

**Comment by codemedic** [comment] 2019-04-02 07:30
Thanks fellows!

**Closed** 2019-04-02 07:30 UTC
