### ISSUE TITLE
"suspend this tab now" and "suspend all other tabs" not working 9 times on 10

### ISSUE THREAD

**Issue by Quake1988** [deanoemcke/thegreatsuspender#787] opened 2018-10-11 12:57 UTC
Before the recent graphic update, it perferctly worked. Now, when I click on "suspend this tab now" and "suspend all other tabs", it does not work and I have to retry many times before the correct action is launched.
Chrome, Windows 7 64.

**Comment by deanoemcke** [comment] 2018-10-12 00:29
This is most probably a duplicate of issue: https://github.com/deanoemcke/thegreatsuspender/issues/735

At least for the 'suspend this tab now' issue.
I'll look further into the 'suspend al other tabs' issue.

**Comment by deanoemcke** [comment] 2018-10-12 00:38
I have committed an optimistic fix for the 'suspend all other tabs issue.
It is available in the latest dev version (v7.0.132).
If you are able to test on this version, it would be much appreciated. Otherwise, just wait and hope that this fixes your issue when the new release gets pushed to the chrome webstore.

**Closed** 2019-02-06 04:05 UTC
Labels: bug-unconfirmed, waiting-on-release
