### ISSUE TITLE
Whenever a tab suspends, it shows me the window of that tab

### ISSUE THREAD

**Issue by massimosclaw** [deanoemcke/thegreatsuspender#884] opened 2019-03-13 13:25 UTC
* Extension version: v7.0.109
 * Browser name & version: Google Chrome 72
 * Operating system & version: macOS mojave

Every time a tab suspends, if I've minimized a window, the window un-minimizes and shows me that suspended tab's window. I'd prefer if it suspends in the background like it used to, and not show me the window. If it's not minimized, and it suspends, it still goes to that tab. I'd prefer it not go to that tab, but just suspend in the background.

**Comment by deanoemcke** [comment] 2019-03-13 22:38
I believe this is a duplicate of: #865
Seems like it was caused by a change in behaviour with chrome.
It should be fixed in the upcoming release.

**Closed by deanoemcke** 2019-03-13 22:38 UTC
