### ISSUE TITLE
Tabs don't un-suspend when viewed by closing adjacent tabs

### ISSUE THREAD

**Issue by jaydge** [deanoemcke/thegreatsuspender#608] opened 2017-10-12 14:26 UTC
The issue originally reported in https://github.com/deanoemcke/thegreatsuspender/issues/550 is back it seems. Screen capture video here: https://www.screencast.com/t/OOfIGYkb. 

To replicate:
1) Set your options to auto-suspend tabs after 20 seconds (short just for testing), and set tabs to auto-unsuspend when viewed. Screenshot of options: https://www.screencast.com/t/KQ2p3XHnr
2) When you click or CTRL+TAB over to a tab, it unsuspends fine, but when you close a neighboring active tab which by default reveals a suspended tab, the suspended tab doesn't auto-unsuspend until user interaction such as clicking it or CTRL+TAB back and forth to it occurs. 

Seen on Chrome Version 61.0.3163.100 (Official Build) (64-bit), on Windows 7 Professional SP1.

**Comment by deanoemcke** [comment] 2017-10-24 06:53
This is a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/519
This was intentionally changed, but due to user feedback it will be reverted back to how it used to work in the upcoming release (v7.x).

**Closed by deanoemcke** 2017-10-24 06:53 UTC
