### ISSUE TITLE
Do not suspend pinned tabs does not work when suspending other tabs

### ISSUE THREAD

**Issue by mwisnicki** [deanoemcke/thegreatsuspender#329] opened 2015-11-21 16:20 UTC
When I press "Suspend other tabs" all tabs get suspended, even pinned ones.

**Comment by deanoemcke** [comment] 2015-11-23 06:15
Yeah, this is intentional - yet maybe not the best idea.  The suspend other tabs function was written to override all other settings (whitelist, pinned tabs, form input, offline etc).

Not sure if this is intuitive or useful though. Would be interested in hearing other peoples opinions.

**Comment by fuzzyweapon** [comment] 2016-01-30 06:09
So, I have to agree.  The very reason I found this issue was because I thought it was a bug.

I think it isn't intuitive because of the language....it kind of conflicts with the tone of the other settings it supercedes, so it'd be important to include language that specifically calls this out.

It might be better to sacrifice some pretty language a little for the sake of usability.

Suggestions:
"Suspend All - Override"
"Suspend Override"
Just exercising how it sounds...
"Override Suspend All"
etc.

**Comment by haridsv** [comment] 2016-12-09 04:45
After installing the extension, the first thing I did was to suspend all tabs, assuming that it would suspend all but the pinned ones. If this option were to override your current settings, how would I achieve this? Should I visit each of the 40 or so tabs I have to suspect only the current one?

From usability point of view, it would make sense to honour the current exclusion settings and allow the "Suspend this tab" to override the settings. The tabs that are excluded are presumably far less in number than the total. E.g., I have 2 pinned tabs and 1 whitelisted tab and 1 current tab out of a total of 40 tabs. If I really meant to suspend all 39 except the current one, then, it would be just a matter of visiting 3 more tabs and using "Suspend this tab".

I can still do that now, i.e., visit these 3 tabs and resume them, but I think the former is the more common use case to make it the default. Besides, there is also a danger of overriding the "Do not suspend tabs that contain unsaved form inputs" and cause me to lose my work.

**Comment by piotrowski** [comment] 2017-06-03 15:26
The confusion here is mainly from the settings option being named "Do not suspend pinned tabs". This should probably say "Do not **auto**-suspend pinned tabs" to be clearer.

Additionally "Suspend other tabs" should probably mention that it ignores all other things and really, really suspends all other tabs. No matter whitelist, pin etc.

And alternatively, and IMHO most importantly there should be a button that really does "Supend other tabs" but still adheres to the whitelist, pinned tabs etc.

**Comment by deanoemcke** [comment] 2017-07-21 20:44
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/553

**Closed by deanoemcke** 2017-07-21 20:44 UTC
Labels: enhancement, prioritised
