### ISSUE TITLE
[Enhancement] Show URL on Suspended Tab

### ISSUE THREAD

**Issue by sundarv85** [deanoemcke/thegreatsuspender#645] opened 2018-01-16 15:42 UTC
Hello,

Great Addon!

Now it shows the Title on a suspended tab. If you could also show the URL on the suspended tab, it would be helpful. Some websites have the same Title for different pages.

**Comment by deanoemcke** [comment] 2018-02-06 16:33
duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/309

**Closed by deanoemcke** 2018-02-06 16:33 UTC
