### ISSUE TITLE
Button or timeout to close suspended tabs

### ISSUE THREAD

**Issue by Ferk** [deanoemcke/thegreatsuspender#84] opened 2014-03-08 18:22 UTC
The next step after suspending a tab that you are not using at all would be to close it, completely releasing it from both memory and the tab bar space.

This is similar to what [the OneTab extension](http://www.one-tab.com/) does with its button. But it would be awesome if this extension (which is open source unlike OneTab) could do something like this, and even better if it was automatic, closing the tabs that have been in suspension for some time. Then being able to reopen them if needed from the suspended tabs history.

**Comment by deanoemcke** [comment] 2015-11-13 05:03
Duplicate of #84

**Closed by deanoemcke** 2015-11-13 05:03 UTC

**Comment by Ferk** [comment] 2015-11-13 08:19
#84 is this same issue, did you thought it was duplicate by mistake?
