### ISSUE TITLE
Suspended tabs don’t always display their 'titles'

### ISSUE THREAD

**Issue by mkz7** [deanoemcke/thegreatsuspender#779] opened 2018-10-08 17:15 UTC
I'm having the same issue reported by Joby Messer on Sep 14, 2018 on the extension's user 'support' page (currently on the "11 - 20 of 103" page).
 
Suspended tabs display only strings such as "chrome-extension://klbibkeccnjlkjkiok" as their 'titles,' which makes it necessary to hover over each tab to find out what its content is (even then, identifying text is embedded in the long text string that's displayed).

![image](https://user-images.githubusercontent.com/16544283/46623516-e60cca00-cafb-11e8-8b09-a05cdd8c8457.png)

When reported by Messer you replied "I haven't had any other reports of this," so I'm adding my voice. 

It doesn't happen all the time. I haven't figured out why it affects particular tabs but not others.

The ability to glance at suspended tabs in the tab bar and immediately identify them is important. 

According to Messer, tabs were previously identified in that way (I only started using TGS recently). Please restore that ability. Thanks.

(Mac OS 13.9.5 – High Sierra)

**Comment by deanoemcke** [comment] 2018-10-10 18:16
@mkz7 can you please tell me what version of the extension you are using?
also, do the tabs show the correct favicon, or is it the default extension icon?
Could it perhaps be the same issue as reported here? https://github.com/deanoemcke/thegreatsuspender/issues/719

**Comment by mkz7** [comment] 2018-10-13 17:44
v. 7.0.109 (Mac)

Tabs show the default icon (in all cases, to my recollection).

e.g.:

![image](https://user-images.githubusercontent.com/16544283/46908184-fef6f000-ceec-11e8-875c-d73590be2768.png)

It appears that it may be related to #719, although that topic appears to deal with an issue related to shutdown/restart, whereas most of the affected tabs in my case go into auto-suspend, apparently based on memory conditions, since I don't have the auto-suspend option active but do have the 'auto-suspend when on low memory' option active).

Thanks.

**Comment by deanoemcke** [comment] 2018-10-14 19:04
@mkz7 Thanks, that's super useful information. I gave you the wrong issue number sorry. #478 is probably more like what you are experiencing (see further down the thread).

I'll investigate the low-memory condition to see if I can replicate on v7.0.109.
I've made a couple of changes since that version which will potentially fix your issue.

And I'll close this thread as a duplicate of #478

**Closed by deanoemcke** 2018-10-14 19:04 UTC
Labels: bug-unconfirmed
