### ISSUE TITLE
Update killed suspended tabs

### ISSUE THREAD

**Issue by Imamadmad** [deanoemcke/thegreatsuspender#521] opened 2017-06-07 09:39 UTC
Yep, lost all the tabs I had suspended.  Couldn't even ctrl+shift+T them back.  Thanks a lot.  I had them sitting there for a reason!

**Comment by gmolop** [comment] 2017-06-07 09:51
Same happened to me just now... very annoying.

I recover my missing tabs reloading the last session in:
`Extension Setting` > `Session management` > `Recent session` > `Reload`

But I'm agree in this would definitely must not happen without warning.

**Comment by QZenn** [comment] 2017-06-07 10:35
WTF?!!!
I had hundreds of Tabs. All of them are gone!
Only active tabs kept in my Chrome.
Please abort updating users for that build!!!

**Comment by ReservedDeveloper** [comment] 2017-06-07 12:16
The README should be updated with the steps provided by @gmolop above. Re-enabling the extension did nothing for me, but that did the trick.

**Comment by oreza** [comment] 2017-06-07 16:04
Even though you can reload the session, tabs go away again after the set interval.

**Comment by deanoemcke** [comment] 2017-06-08 16:51
Closed as duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/512

For the official issue of handling lost tabs due to update please refer to: https://github.com/deanoemcke/thegreatsuspender/issues/163

**Closed by deanoemcke** 2017-06-08 16:51 UTC
