### ISSUE TITLE
Title of the tab

### ISSUE THREAD

**Issue by raja777m** [deanoemcke/thegreatsuspender#443] opened 2016-10-10 03:27 UTC
Hello,
I use Google's sync option to access the opened tabs from other devices, so, my issue here is, when I try to access the tabs, the names are displayed as "Suspended Tabs" instead of the actual title.
Can you guys please update the tabs in a way, I can see the title form other devices.
Anyway, we can see the grayed out tabs on the desktop version.
![fullsizerender](https://cloud.githubusercontent.com/assets/4664398/19226339/ea1eef50-8e77-11e6-82c2-a8576df092a9.jpg)
![screen shot 2016-10-09 at 11 27 24 pm](https://cloud.githubusercontent.com/assets/4664398/19226343/f8015b94-8e77-11e6-8157-b5039eda4e23.jpg)

**Comment by Bachomp** [comment] 2016-10-19 21:27
Yes please, don't rename the tab. The grey title text is enough. When you have 100 tabs open they all say 'Suspended Tab' How are we suppose to determine what tab is a what at a glance.

**Comment by icemanyu** [comment] 2016-10-28 06:17
Yes. Attach the original tab title will be great from other device's chrome APP, especially for mobile. (The desktop version can judge by the redirect url, but unable to do it on cellphone...)

**Comment by DanAtkinson** [comment] 2016-10-31 12:03
It looks like this has been fixed in a previous [commit](https://github.com/deanoemcke/thegreatsuspender/commit/796a85ed252250323b3ea85befb9c7dc5c2df905) but the author is somewhat lackadaisical when it comes to releases.

**Comment by Bachomp** [comment] 2016-11-01 04:22
wow, commits made but no new release since sept 2015 :(

**Comment by deanoemcke** [comment] 2017-07-25 17:22
This has been fixed and released on the chrome webstore (v6.30)
Also, it is a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/225

**Closed by deanoemcke** 2017-07-25 17:22 UTC
