### ISSUE TITLE
tab suspension causes window/workspace switch unexpectedly

### ISSUE THREAD

**Issue by quentusrex** [deanoemcke/thegreatsuspender#912] opened 2019-04-07 00:04 UTC
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.0.109
 * Browser name & version: Chrome 73.0.3683.86
 * Operating system & version: OSX 10.14.3 and 10.14.4

And please also do a search for your request/bug before create a new one thanks!

When a tab is being suspended the OSX window/workspace switches unexpectedly to the window with the tab that is being suspended. The suspended tab isn't brought into focus, just the window that contains the tab. Use case is working with chrome with 3-7 windows open, and each window with more than 3 tabs each, and each window set in 'full screen' mode.

**Comment by Jollfye** [comment] 2019-04-07 11:51
[update](https://github.com/deanoemcke/thegreatsuspender/issues/911#issuecomment-480492720) ur TGS extension

**Comment by ErikHumphrey** [comment] 2019-04-07 21:41
Possible duplicate of #865, which was fixed.

**Comment by deanoemcke** [comment] 2019-04-08 11:10
Be careful if uninstalling the extension. Make sure you unsuspend all your tabs first!

**Closed** 2019-04-08 11:09 UTC
Labels: duplicate
