### ISSUE TITLE
Tab won't suspend

### ISSUE THREAD

**Issue by Pascal666** [deanoemcke/thegreatsuspender#631] opened 2017-12-18 00:33 UTC
After submitting my zip code at https://www.antennasdirect.com/transmitter-locator.html I can't seem to get the tab to suspend.  I've tested on both Windows and Linux.

**Comment by deanoemcke** [comment] 2018-02-06 18:08
Can you give me a bit more information?
Do you mean the tab doesn't auto-suspend? Or that you can't manually suspend it (by clicking on 'Suspend this tab' in the popup menu).

Also, do you have the 'Never suspend tabs that contain unsaved form inputs' option checked?
And what version of the extension are you on?

**Comment by Pascal666** [comment] 2018-02-09 13:23
I type in my zip code, hit enter, then try to manually suspend the tab, and nothing happens.  I've tested with TGS v6.30 on both Linux and Windows.

"Do not suspend tabs that contain unsaved form inputs" only shows up as an option after I enable auto-suspend.  I had auto-suspend disabled, but just enabled it and unchecked all the "Do not suspend" options and that tab will not auto-suspend either.  Clicking on TGS says "Tab will be suspended automatically.", but it doesn't.

If Screen capturing is disabled, the tab suspends normally.

**Comment by Pascal666** [comment] 2018-04-17 17:36
I just tested again on both Windows and Linux, and now that one works perfectly.  This one works on Linux, but not Windows: http://www.instructables.com/id/Hack-Make-Your-Digital-Picture-Frame-Go-Live/
The developer console output appears to be very useful.  Right after I tell it to suspend it gets a 404 and then "Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported".  I switched from full page to visable only, tried in a few different spots on the page, and got the same output.  Full output:

> c_small.png:1 GET http://www.instructables.com/intl_static/img/license/c_small.png 404 (Not Found)
> Image (async)
> loadImage @ html2canvas.min.js:7
> u.Preload @ html2canvas.min.js:7
> (anonymous) @ html2canvas.min.js:8
> setTimeout (async)
> t.html2canvas @ html2canvas.min.js:8
> generatePreviewImg @ contentscript.js:141
> (anonymous) @ contentscript.js:267
> EventImpl.dispatchToListener @ VM351 extensions::event_bindings:403
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> EventImpl.dispatch_ @ VM351 extensions::event_bindings:387
> EventImpl.dispatch @ VM351 extensions::event_bindings:409
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> messageListener @ VM358 extensions::messaging:240
> EventImpl.dispatchToListener @ VM351 extensions::event_bindings:403
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> EventImpl.dispatch_ @ VM351 extensions::event_bindings:387
> EventImpl.dispatch @ VM351 extensions::event_bindings:409
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> dispatchOnMessage @ VM358 extensions::messaging:392
> contentscript.js:149 canvas: [object HTMLCanvasElement]
> contentscript.js:150 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
>     at Object.onrendered (chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:150:46)
>     at Object.o.complete (file:///C:/Users/Pascal/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/klbibkeccnjlkjkiokjodocebajanakg/6.30_0/js/html2canvas.min.js:8:2419)
>     at o (file:///C:/Users/Pascal/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/klbibkeccnjlkjkiokjodocebajanakg/6.30_0/js/html2canvas.min.js:7:28352)
>     at Image.e.onerror (file:///C:/Users/Pascal/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/klbibkeccnjlkjkiokjodocebajanakg/6.30_0/js/html2canvas.min.js:7:30140)
> onrendered @ contentscript.js:150
> o.complete @ html2canvas.min.js:8
> o @ html2canvas.min.js:7
> e.onerror @ html2canvas.min.js:7
> error (async)
> p @ html2canvas.min.js:7
> loadImage @ html2canvas.min.js:7
> u.Preload @ html2canvas.min.js:7
> (anonymous) @ html2canvas.min.js:8
> setTimeout (async)
> t.html2canvas @ html2canvas.min.js:8
> generatePreviewImg @ contentscript.js:141
> (anonymous) @ contentscript.js:267
> EventImpl.dispatchToListener @ VM351 extensions::event_bindings:403
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> EventImpl.dispatch_ @ VM351 extensions::event_bindings:387
> EventImpl.dispatch @ VM351 extensions::event_bindings:409
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> messageListener @ VM358 extensions::messaging:240
> EventImpl.dispatchToListener @ VM351 extensions::event_bindings:403
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> EventImpl.dispatch_ @ VM351 extensions::event_bindings:387
> EventImpl.dispatch @ VM351 extensions::event_bindings:409
> publicClassPrototype.(anonymous function) @ VM357 extensions::utils:138
> dispatchOnMessage @ VM358 extensions::messaging:392

**Comment by deanoemcke** [comment] 2018-08-21 03:46
This sounds like a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/657
Although, in the most recent version (v7.0.102) the links you posted now seem to capture without issue.

**Closed by deanoemcke** 2018-08-21 03:46 UTC
Labels: bug-unconfirmed
