### ISSUE TITLE
All suspended tabs appear to be lost

### ISSUE THREAD

**Issue by TN2001** [deanoemcke/thegreatsuspender#524] opened 2017-06-07 19:18 UTC
All suspended to be lost. Rebooted Chrome today because,..again...all suspended tabs had disappeared. 

So I rolled back to a saved set of tabs using Session Buddy. This has restored all my tabs in the past, including the suspended ones (in a suspended state). 

This time, it did not work. Instead, clicking on a suspended tab returned this message:

> Your file was not found
> 
> It may have been moved or deleted.
> ERR_FILE_NOT_FOUND

Are all my suspended tabs, meaning almost all tabs I had up, truly lost forever? 

Sorry, but WTF is going on with this extension? It's been nothing but days and days of trouble ever since the big changes. Is the extension stable or not?

And how can I get my tabs back?

Thanks,

TN

**Comment by greenitthe** [comment] 2017-06-07 20:00
What I did was open the suspended tabs up, don't unsuspend them, and copy the URL at the end. Pipe that into a URL decoder and you have the link back, but it is a pain if you have a bunch of tabs.

**Comment by TN2001** [comment] 2017-06-08 01:32
Thanks, James. I have 175 tabs and not the kind of time this requires,
since I use these tabs for work, for research.

1. How on earth did this happen? I mean that; I'd like to know.

2. What does it mean that the file "has been moved or deleted"? If moved,
can it be recovered? If deleted, how? Why?

3. I see a popup asking if this extension "makes me happy" and requesting
money. Are you people kidding?

Yours in great frustration,

T

**Comment by TN2001** [comment] 2017-06-08 01:35
Finally, would you please let us all now when it's safe to re-enable your
extension. I like the function. I just want it to work and not have to go
through this exercise twice.

Thanks,

T

**Comment by TN2001** [comment] 2017-06-08 01:47
Oops. James, I assumed you were answering on behalf of the design team. If that's not the case, would the design team please address my questions?

Thanks, 

T

**Comment by gregoryka** [comment] 2017-06-08 04:43
This is addressed in #512 and #513. Specifically this <a href="https://github.com/deanoemcke/thegreatsuspender/issues/512#issuecomment-306356434">comment</a>

**Comment by deanoemcke** [comment] 2017-06-08 16:51
Closed as duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/512

For the official issue of handling lost tabs due to update please refer to: https://github.com/deanoemcke/thegreatsuspender/issues/163

**Closed by deanoemcke** 2017-06-08 16:52 UTC

**Comment by TN2001** [comment] 2017-06-11 20:06
Thanks, Dean.

Re other threads that say no auto updating, how will we users know an update is available?

TN
