### ISSUE TITLE
Remember Whitelisted sites across computers

### ISSUE THREAD

**Issue by EduCampi** [deanoemcke/thegreatsuspender#593] opened 2017-09-13 17:25 UTC
Hi,
I usually switch to multiple computers when I travel, and it's a pain to have to re-whitelist the email, chat, and other webpages I use for work.
Could we save the whitelist settings to the chrome session storage? that way they'll be persistent across computers as long as I'm using the same account.
 More info about 'chrome.storage.sync' at https://developer.chrome.com/apps/storage

Thanks!

**Comment by dragon788** [comment] 2017-09-28 15:51
This is probably a duplicate of #262 so you if you'd like you can close this and Subscribe to that one for updates. It appears to be partially implemented already.

**Closed** 2017-10-23 21:43 UTC
Labels: duplicate
