### ISSUE TITLE
"Suspend other tabs" doesn't suspend the right tabs (current active window)

### ISSUE THREAD

**Issue by Zoooook** [deanoemcke/thegreatsuspender#475] opened 2017-02-27 08:26 UTC
I typically have several windows open with several tabs in each. Most of the time if I click "Suspend other tabs" it either doesn't work or it suspends tabs in a different window. My workaround is to move a tab into its own window, then move the rest of the tabs into that window, and this seems to refresh what it thinks of as the current window, and then the function works correctly for that window.

**Comment by deanoemcke** [comment] 2017-07-19 02:00
Could you please let me know if you are still encountering this issue on the latest release (v6.30)?

**Comment by deanoemcke** [comment] 2017-07-19 02:09
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/325

**Closed by deanoemcke** 2017-07-19 02:09 UTC
Labels: bug-unconfirmed
