### ISSUE TITLE
Opera Addon

### ISSUE THREAD

**Issue by shwetank** [deanoemcke/thegreatsuspender#387] opened 2016-04-14 09:45 UTC
Opera supports the chromium extensions model. It would be great if you could submit this extension to the [opera addons site](https://addons.opera.com) so that opera users also can install and use the extension. (You could even submit the file in .crx format).

**Comment by deanoemcke** [comment] 2017-07-25 16:10
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/387Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/387

**Closed by deanoemcke** 2017-07-25 16:10 UTC
Labels: duplicate
