### ISSUE TITLE
Screencapture/screenshots on QHD screens, scale bad

### ISSUE THREAD

**Issue by NickNiebling** [deanoemcke/thegreatsuspender#211] opened 2015-05-22 09:00 UTC
When Chrome is used on a QHD resolution, chrome will adjust pixel sizing when rendering, so 1 px becomes 4 px.

When the great suspender takes a screenshot, it will store each scaled px as 4 px (and that might be best practice!), but when the image is displayed, the pixels are scaled again and displays as 16 px (instead of 4 px as it should).

I'm using 2 screens - 1 is QHD and another is FullHD - chrome knows when I'm changing between screens instant. Maybe that is a property available in the API? And maybe displaying the image could be scaled down to 50% width and 50% height, in case of QHD?

**Comment by Diablo-D3** [comment] 2015-06-19 20:45
Scaling down isn't the right answer here. It needs to remember what the real size of the window is in CSS px (which are defined in angular degrees, as in, equivalent to non-HiDPI pixels on a standard 96 dpi monitor), and then just display the image normally (img width and height set to the CSS px, not actual pixel sizes of the captured image).

**Comment by deanoemcke** [comment] 2017-10-24 06:46
Closing as possible duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/602

**Closed by deanoemcke** 2017-10-24 06:46 UTC
