### ISSUE TITLE
File was not found

### ISSUE THREAD

**Issue by greenitthe** [deanoemcke/thegreatsuspender#516] opened 2017-06-07 02:05 UTC
In v6.30 unsuspending any tabs from before the update (tabs suspended after are fine as far as I can tell) are redirecting to chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/false and showing this error:
![suspender-error](https://user-images.githubusercontent.com/1825286/26859182-9d8c266c-4afb-11e7-8913-93d29b3f47e5.png)
Reloading from session manager only opens a few of the tabs, resuspending from session manager opens all tabs but with the same issue still affecting them.

Note, after unsuspending the tab, it is impossible to hit the back button to revert to the suspended state, causing loss of tabs and the URL.

**Comment by greenitthe** [comment] 2017-06-07 02:14
It appears the affected tabs are missing a header bar:
![suspender-error-2](https://user-images.githubusercontent.com/1825286/26859351-b70f5e46-4afc-11e7-9203-1c44894ff576.png)
 as well as the site icon:
![suspender-error-3](https://user-images.githubusercontent.com/1825286/26859393-0500ec82-4afd-11e7-9161-bcf607a7aad0.png)

**Comment by deanoemcke** [comment] 2017-06-08 19:35
@greenitthe do you have any idea which version of the extension you had before the update? did the UI look entirely different?
This is a pretty serious issue. I'd like to find out more, but it's pretty hard to test. I wonder if anyone else has encountered this issue?

Perhaps you would like to make a comment on [this guide](https://github.com/deanoemcke/thegreatsuspender/issues/526) i made for recovering from tab loss. I will be redirecting all users suffering from lost tabs there, and they might be able to report the same issue as you.

**Comment by bend1234** [comment] 2017-06-10 16:54
I'm having this same issue on one of my systems as well. I lost all of my tabs during the update issue earlier this week, but I was able to recover using a session buddy backup. However, clicking on any of the older suspended tabs now gives the "Your file was not found error".

**Comment by deanoemcke** [comment] 2017-06-11 04:40
@bend1234 in your session buddy backup, can you post one of the urls of a tab that is failing? and also, on a failed tab, can you open the developer console and see if there are any errors in the console?

**Comment by TN2001** [comment] 2017-06-11 22:18
Same problem. I used Session Buddy to restore all lost tabs (175) and then used a URL decoder to paste the real link into each one with TGS set to suspend in "5 days". Painful, but it worked. This is no more than 2 days ago.

**Comment by bend1234** [comment] 2017-06-11 23:48
I don't see anything in the developer console, here's an example URL:
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#url=https%3A%2F%2Fwww.tekthing.com%2F

**Comment by deanoemcke** [comment] 2017-06-13 18:21
Ok. I can see from that url what the issue is. That url is from a very old version of the extension. I though that the new release would handle these old urls properly, but it appears not :(
Someone [once made a bookmarklet](https://github.com/deanoemcke/thegreatsuspender/issues/216) to help manually unsuspend bad urls. I have tested it and it appears to still work on the above urls. 

Here are the original instructions to save and use the bookmarklet (thanks @joeytwiddle):

1. Hit Ctrl-Shift-B to show your Bookmarks Toolbar.
2. Right click to create a new "page" there, call it `Unsuspend` and give it the following URL:
   
   ```
   javascript:document.location=decodeURIComponent(document.location.hash.replace(/.*url=([^&]*).*/,'$1'));(void 0);
   ```
3. The next time you are on a suspended page, tap your bookmarklet and it will unsuspend.  :)

This is a workaround for now. I'll try to add a fix so that future versions will handle these old urls appropriately.

**Comment by bend1234** [comment] 2017-06-15 04:14
Thanks, that worked for all of the old tabs

**Comment by Colt15** [comment] 2017-06-24 17:49
@deanoemcke That fix doesn't appear to work for me, and clicking on the Great Suspender icon on the extension bar also brings up the "Your file was not found" page in the popup. Do you think reinstalling the extension might help?

**Comment by deanoemcke** [comment] 2017-06-24 18:39
Uninstalling will remove all your tabs. Back them up with the session buddy extension first!
Not sure if reinstalling will help as I haven't made a fix for this issue yet. 

Can you please copy and paste one of the problem urls here so I can see what's going on?

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Colt15** [comment] 2017-06-24 21:56
Sure, I've got a bunch.
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=(30)%20HEREINMYGARAGE.mwv%20-%20YouTube&uri=https://www.youtube.com/watch?v=0GIwTG8V-Ko

chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=Isometric%20Survival%20Game%20Distrust%20Channels%20John%20Carpenter%E2%80%99s%20The%20Thing%20%7C%20Rely%20on%20Horror&uri=http://www.relyonhorror.com/latest-news/isometric-survival-game-distrust-channels-john-carpenters-the-thing/

chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=Welcome%20to%20Steam&uri=http://store.steampowered.com/

Many more other than that. There are also pages which appear to be immune to it, but I can't seem to figure out what causes it. On some pages I can use the Back action and it effectively takes me back to the website. I recently installed an HTML5 Autoplay disabler, and I thought that might be related, but based on this thread I'm guessing it isn't.

**Comment by deanoemcke** [comment] 2017-06-25 19:06
@Colt15 that really seems like a different issue to the others. Those urls look fine to me. Uninstalling and reinstalling really might help you. But you'd have to backup your suspended tabs with session buddy first and then restore the session afterwards with session buddy. 

Sorry but I can't understand what might be happening for you. You could always try looking in the dev console for errors on one of the broken pages?

**Comment by Colt15** [comment] 2017-06-26 22:44
Darn, well eventually it started eating up all my tabs so I had no choice but to reinstall it. That fixed everything the issue, although now I have to try and remember what was on my whitelist haha.

**Closed** 2017-07-25 15:30 UTC
Labels: bug-confirmed, caused-by-old-version-of-extension?, prioritised
