### ISSUE TITLE
Going back re-suspends tab

### ISSUE THREAD

**Issue by Barleyman** [deanoemcke/thegreatsuspender#128] opened 2014-10-02 12:38 UTC
As it says. With 5.26 a tab that's un-suspended will be re-suspended if I hit "back" button. 

This is pretty evident on real-estate pages where you'd want to go back to see the listing from invidual property view.

**Comment by Diablo-D3** [comment] 2015-06-10 06:58
Has this bug been fixed? https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history seems to do exactly what you want, and I think Chrome supports that JS API.

**Comment by deanoemcke** [comment] 2015-07-03 04:35
@Diablo-D3 Unfortunately not. In the instances where a tab is unsuspended by clicking on the suspended tab, it will behave nicely and the page will call window.location.replace (causing the unsuspended version to replace the suspended one).
In all other instances of unsuspension though (automatic tab unsuspend, or clicking unsuspend all), it will cause a history item to be created. This is due to the fact that suspended pages do not have any listeners (to reduce the memory usage of these tabs) and hence there is no way to get them to execute js remotely.

**Comment by deanoemcke** [comment] 2015-11-13 02:17
this is a duplicate of #323 which has now been fixed~

**Closed by deanoemcke** 2015-11-13 02:17 UTC
