### ISSUE TITLE
Feature request: Show page title in Recent Tabs

### ISSUE THREAD

**Issue by eagle0042** [deanoemcke/thegreatsuspender#225] opened 2015-06-05 19:34 UTC
Hi Dean,

Thanks for this extension, it's brilliant and helps me manage Chrome's memory consumption even with all of my tabs. I do have one request though. I use Chrome and this extension on multiple computers, and I use the Recent Tabs feature of Chrome to view tabs I have opened on other machines. However, once the tab is suspended, I can no longer tell which tab is which, without having to hover over every link to view the URLs. Is is possible to display what the page title was before it was suspended, maybe something like "Suspended Tab - Facebook" or "[S] - Facebook"? I've attached a image of what I see below.

![image](https://cloud.githubusercontent.com/assets/3215663/8013517/75b5c330-0b8f-11e5-84e5-6a0939aedbb5.png)

The only tab I can see is the tab that was last viewed on the other computer.

Thanks!
Blake

**Comment by deanoemcke** [comment] 2015-06-08 06:37
This is a duplicate of issue: #164 
Unfortunately, I haven't found a way around this just yet. It is actually due to a bug in the chrome application when syncing history: https://code.google.com/p/chromium/issues/detail?id=491325

**Comment by deanoemcke** [comment] 2015-06-09 19:00
Making this the master issue for this problem as it has a nice screenshot :)

**Comment by juddrgledhill** [comment] 2015-07-06 19:29
I would be a fan of this approach:

"[S] - Facebook"

I experienced this issue today and came to open a bug. Already here.

**Comment by deanoemcke** [comment] 2015-07-15 01:13
@juddrgledhill this thread is actually discussing the issue of tab titles not being synced across devices. however it appears that you are also suggesting that the tab title be modified as well to indicate a suspended state. there is actually a separate issue already logged for this: #240

**Comment by thecrazy** [comment] 2015-08-11 17:12
I also would like to see the real titles instead "Suspended tab".

As far as I am concerned, I find that the icon itself is hint enough that the page has been suspended, no need to append anything to the title in chrome://history/

To work around the mechanics of the history synchronization, can't you read the title of a page before suspending it and set it as the suspended tab's title? There may be some redesign required in the extension but surely there is a way.

**Comment by deanoemcke** [comment] 2015-11-04 06:52
@thecrazy The problem is that once a tab navigates to a new url, the title that the page has on initial load is the title that the history will store. Changing the title of a tab subsequently will have no effect on the history entry.
When a tab suspends, it navigates to a new url (suspended.html) which has a title of 'Suspended Tab'. The title is then subsequently updated, but this change is not reflected in the history. There is no way to change the title of this tab BEFORE the page loads. It can only be done with javascript AFTER page load.

**Comment by deanoemcke** [comment] 2015-11-13 02:14
OK. So I said that above, but it turns out that if you change the page title early enough with javascript, it does make it into chrome's recent history. So that's been fixed which is great. Unfortunately, it doesn't work for the favicon though :(
And of course, the url is always going to be a suspended url.

**Comment by kidpixo** [comment] 2016-07-08 13:24
I have the same issue. 
A stupid solution (don't know if it's doable) could be to dynamically create a `suspended.html` with with custom title and/or favicon for each tab.
This way, when you navigate off the page you are landing on a page with the same title or modified with `[S] - Old Title` or whatever. 
Memory overhead is plausible, but we are in the range of 1KB/Tab, typical user will be in the range of tents of KB, nothing scary today.
I don't know if an extension could create pages and where it could store this stuff.

Cheers.

**Comment by nikolaypavlov** [comment] 2016-08-16 20:02
Same here on 6.21. Titles that was suspended on my PC are not available on chrome mobile. 
![screenshot 2016-08-16 23 01 46](https://cloud.githubusercontent.com/assets/2743635/17713810/7a93d9ee-6405-11e6-961d-f043435c696d.png)

**Comment by deanoemcke** [comment] 2017-06-08 16:29
This issue covers a very narrow portion of a much larger issue. Specifically, when viewing 'recent tabs' on another device, suspended tabs show 'Suspended Tab' as the page title.
This has been fixed and is available on the chrome webstore in v6.30.

This does NOT address:

- Clicking on a suspended tab link does not open the page. It instead sets the url as something like: `chrome-extension://xxxxxxxx/suspended.html#ttl=<Page Title>&uri=http...`
As a work around for this, you can manually edit the above url, deleting everything before the uri= part, and it should load the original page for you.

- Favicons for these suspended tabs are not present. It shows the default 'new page' icon

For the broader issue of tab syncing across devices generally not working, please refer to this issue in future: https://github.com/deanoemcke/thegreatsuspender/issues/46

**Closed by deanoemcke** 2017-06-08 16:29 UTC
Labels: fixed, waiting-on-release
