### ISSUE TITLE
Add option to allow "Suspend all others tabs" to ignore whitelist

### ISSUE THREAD

**Issue by retrospec13** [deanoemcke/thegreatsuspender#738] opened 2018-08-26 16:28 UTC
Previously the GS chrome extension would suspend all tabs regardless of "eligibility" or not.

That was useful in closing any open tabs other than one you were primarily using.

Now with the latest update, there is no way to close tabs that are URL whitelisted unless you do it manually.

This feature should be reversed or there should be an additional option to supersede whitelisted URLs.

Otherwise, if we have 20 tabs open from a whitelisted URL and we want to suspend them, we now have to do it manually, 1 by 1.

Now the only way to get around this is to have no whitelisted URLs and instead put them all on 10 minute or higher auto suspend and then we can use the normal functionality of "suspend all other tabs".

**Comment by deanoemcke** [comment] 2018-08-27 01:01
Actually, the 'suspend all tabs in all windows' option will actually force all tabs, whitelisted or not, to suspend.
It's not well documented sorry, and a bit odd i'll admit that it happens on this option and not the 'suspend other' option.
Does this help you?

**Comment by peterlaws** [comment] 2018-09-02 07:34
This option doesn't work for me, the "Force tabs ...." option should be used (only available in the context menu), but it also suspends the active tab.

**Comment by deanoemcke** [comment] 2018-09-04 01:59
Ok, that's for the feedback. I've updated the title of the issue to suggest this should be made into a preference.

**Comment by deanoemcke** [comment] 2018-09-04 02:08
@peterlaws can you give me an idea of what you're after ideally?
it's just a bit of a grey area for me. i can understand you might expect whitelisted tabs to be included in the 'suspend all other tabs' action. and probably pinned tabs also (even with the option to never suspend pinned tabs turned on).
but what about tabs that have been temporarily paused? and tabs that are currently receiving form input?

**Comment by retrospec13** [comment] 2018-09-04 18:45
The "Suspend all other tabs" does not force close all open tabs as it did in the previous version of the app.

The previous version of this app did force close all windows regardless of whitelist or not and that is a valuable feature when we want to keep the tabs available for future use but need to suspend them for the time being.

What were the changes made to the force close section that would prohibit this?

**Comment by deanoemcke** [comment] 2018-09-05 00:44
@retrospec13 sorry, that comment above was for you. thanks for working that out :)

first of all, just to clarify, when you talking about 'closing' tabs, i assume you mean suspending? there was never any option to close tabs automatically, so i assume i'm correct with this assumption.

and second clarification, we are only talking about the 'suspend all other tabs' option from the popup menu. NOT the 'force suspend all tabs in all windows' option in the right-click context menu.

so, assuming the two things above, i can confirm that this latest release has changed the behaviour of the 'suspend all other tabs' action, so that it will now only affects tabs that would have automatically suspended anyway (ie. not whitelisted tabs, or pinned tabs if the 'never suspend pinned tabs' option is checked).

in effect, the 'suspend all other tabs' action just fast forwards the timer on all tabs and make those that would have suspended eventually, suspend right away. those that would not have suspended are not affected.

my question to you is how you would like this to change. you've already stated that you'd like it to suspended whitelisted tabs. and you've also stated that you DON'T want the currently focused tab to suspend.

i would like to know what you expect to happen to some of the other tabs. like:
- tabs that have unsaved form input
- tabs that you have specifically requested not to suspend by choosing the 'not now' link in the popup.

**Comment by deanoemcke** [comment] 2018-09-05 16:30
I'm unsure why you keep using the word 'closed'? That implies the tab will disappear which is never what this extension has done or (i think) should do.

Once again, I'm going to assume you mean 'Force all tabs to suspend in this window' (except currently focused tab).

So that really just brings us back to my earlier two questions. And it seems that yes, you'd like tabs with unsaved form input to suspend, even if that means losing whatever you've typed in there.
And I'm going to assume that you would also expect tabs that you've explicitly asked to not suspend (via the 'not now' option in the popup menu) to also suspend.

My personal thoughts on this:
I don't think this is different enough from the current 'suspend all other tabs' option to warrant an additional option in the popup menu.
I think at the very least, the current option needs to be reworded slightly to be more clear as to exactly what it does.
And possibly we could add an addition option to configure how this action works.

An alternative approach could be to have just a single action for suspending multiple tabs, and then it prompts you for whether you'd like included tabs with unsaved form inputs, paused tabs, and which windows to target.

**Comment by peterlaws** [comment] 2018-09-08 16:34
> Once again, I'm going to assume you mean 'Force all tabs to suspend in this window' (except currently focused tab).

Is there any reason why this option is only available in the context menu, and not from within the icon menu as well?

**Comment by retrospec13** [comment] 2018-09-08 16:40
> Is there any reason why this option is only available in the context menu, and not from within the icon menu as well?

The option you're referring to doesn't exist at all.

There is only suspend all tabs in all windows or suspend other tabs which doesn't force suspend all tabs.

**Comment by kankaristo** [comment] 2018-09-08 16:45
I agree. The main purpose of the whitelist, in my opinion, is to stop *automatic* suspension, I don't want it to stop manual suspension (i.e. suspend all other tabs, or suspend selected tabs).

Same thing for tabs that I've set to pause suspension ("Not now"), I only want that to stop *automatic* suspension, not to make it a pain to manually suspend multiple tabs.

Another option would be to have "Suspend all other tabs" to work the way it does now (whitelisted and paused tabs wouldn't suspend), and "Suspend selected tabs" would force suspend all selected tabs (ignoring the whitelist and paused tabs). That way you could just select all tabs in the window and suspend them, no need to toggle settings. But the wording should probably be changed to "Force suspend selected tabs" to avoid confusion.

That way you wouldn't need to add a setting or a new option in the menu.

**Comment by retrospec13** [comment] 2018-09-08 18:49
> What is this then, Scotch mist?

That's the force **all** tabs in all windows feature.

That's not the feature we're discussing.

We're discussing force suspend all tabs in **this** window **except** the active tab

Please re-read everything.

**Comment by peterlaws** [comment] 2018-09-08 19:10
Same option though...... I just asked why it's only in the context-menu..... So my question is valid.....

**Comment by retrospec13** [comment] 2018-09-08 19:12
It's not the same option.

They are two different features.

**Comment by deanoemcke** [comment] 2018-09-10 00:58
@peterlaws there is no good reason why this is only in the context menu. i guess perhaps i just thought it probably wasn't used very often and didn't want it to clutter up the popup menu. i'm open to perhaps add this in? but not sure as it has the potential to suspend tabs with unsaved form input and i dont want users to accidentally click this..

@kankaristo that's an interesting point about selected tabs. i hadn't realised it prevents whitelisted selected tabs from suspending. that really doesn't make sense. in this case it really should force all selected tabs to suspend, even ones with unsaved form input (in my opinion).

i'm still on the fence about the 'all other tabs' option. it's worth noting that it used to behave exactly as you are requesting (it would force suspend all other tabs in the window regardless of the 'never suspend' settings). however, there were multiple bug reports about this which seemed to indicate that that behaviour was unintuitive. see:
https://github.com/deanoemcke/thegreatsuspender/issues/553
https://github.com/deanoemcke/thegreatsuspender/issues/329
https://github.com/deanoemcke/thegreatsuspender/issues/437
https://github.com/deanoemcke/thegreatsuspender/issues/567
https://github.com/deanoemcke/thegreatsuspender/pull/462
https://github.com/deanoemcke/thegreatsuspender/issues/329
the large number of these raised issues makes me very hesitant to revert this behaviour. however, most of these issues are people wanting the 'pinned tabs' option respected. but i think this holds equally as true for whitelisting.

perhaps @kankaristo's suggestion of using suspend selected tabs (and changing it to force suspend) would be an adequate workaround for the minority of people who want to also suspend whitelisted/pinned tabs?

alternatively, i would consider adding an extra option 'force suspend all tabs in this window' to the right-click context menu. @peterlaws once again, not putting this in the popup menu :/

thoughts everybody?

**Comment by retrospec13** [comment] 2018-09-10 02:29
@deanoemcke Why are you hesitant to put 'force suspend all tabs in this window' in the pop-up menu?

I would say at the very least, add it to the right-click context menu for now and lets see how that goes.

**Comment by deanoemcke** [comment] 2018-09-10 20:34
@retrospec13 i'm hesitant because i'm unsure how many people have a need for these actions. if it's only a few, then omitting them from the popup menu provides a better user experience for the majority of users (due to a cleaner, more comprehendible menu).

it's the same reason we have omitted the " in this window" text as well (ie: instead of "suspend all other tabs _in this window_").

**Comment by deanoemcke** [comment] 2018-09-13 19:45
@kankaristo 

> Another option would be to have "Suspend all other tabs" to work the way it does now (whitelisted and paused tabs wouldn't suspend), and "Suspend selected tabs" would force suspend all selected tabs (ignoring the whitelist and paused tabs). That way you could just select all tabs in the window and suspend them, no need to toggle settings. But the wording should probably be changed to "Force suspend selected tabs" to avoid confusion.

I just looked into this, and "Suspend selected tabs" already does ignore whitelist etc. I've tested it, and this does look like it is currently a viable workaround for suspending those tabs that do not get triggered with the 'suspend all other tabs' action.

**Comment by retrospec13** [comment] 2018-09-13 20:36
@deanoemcke where are you seeing "Suspend selected tabs" ?

Currently we need a way to over-ride whitelisted and input tabs. As I can see now, there's no viable option for this other than manually doing it 1 by 1 which is not efficient.

Can you put in an option somewhere that will force suspend tabs in the active window?

**Comment by deanoemcke** [comment] 2018-09-17 21:00
@retrospec13 if you select multiple tabs in chrome (by holding down shift and then clicking another tab) then two extra items will appear in the extension popup menu given you the option to suspend / unsuspend all the selected tabs.

in the most recent dev version, these options have been permanently added to the right-click menu and also available as keyboard shortcuts.

Also, in this latest dev version, there is an option in the right-click menu (and keyboard shortcut) to force suspend all tabs in the active window.

Here's a screenshot :)

![image](https://user-images.githubusercontent.com/1051763/45650054-17fdb400-ba9b-11e8-8e19-e9784e301d09.png)

**Comment by deanoemcke** [comment] 2018-10-03 19:02
@retrospec13 dev version will be released very shortly. can you please elaborate on what suggestion is not working? I have tested and if you select multiple tabs (via shift click) then chose 'suspend selected tabs' from the popup menu, it DOES override whitelisted urls (ie: it suspends all selected tabs).

Does this not work for you?

**Closed** 2019-02-06 04:05 UTC
Labels: feature, waiting-on-release
