### ISSUE TITLE
Capturing screenshot should keep scroll position

### ISSUE THREAD

**Issue by mrudat** [deanoemcke/thegreatsuspender#436] opened 2016-09-07 09:34 UTC
I manually suspended a tab which was scrolled around halfway down (because there's some obnoxiously expensive background script on that page), but before taking the screenshot, it was scrolled to the top of the page. I would much prefer if a screenshot could be captured of the current position within the page, to more closely match the behaviour if the tab were to have been left alone.

**Comment by jddcef** [comment] 2016-09-22 09:42
Duplicate of #229

**Closed** 2016-09-25 23:08 UTC

**Comment by mrudat** [comment] 2016-09-25 23:10
Closed as duplicate of #229
