### ISSUE TITLE
1 click suspend option and favicon

### ISSUE THREAD

**Issue by rctneil** [deanoemcke/thegreatsuspender#32] opened 2013-03-29 21:20 UTC
1. Can a keyboard shortcut be added for suspending current tab?

2. Can we have a 1 click button for suspending current tab?

3. Can you add an option to somehow visually see if a tab is suspended, (something different to the current dimming of the favicon as I have found it's sometimes not obvious. Maybe overlay a coloured translucent square ontop of the favicon so it's very easy to tell what is suspended and what is not.

**Comment by deanoemcke** [comment] 2015-01-13 11:48
For OPs points 1) and 2): This is a duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/11 and has been resolve in the form of a configurable keyboard shortcut which can be set in the options page.
For issue 3) I feel that the current semi-transparent favicons work well and would personally not want anything less subtle than that. I may support optional favicon decoration in future, but you would need to open that request as it's own issue.

@zldrq Your favicon issues may have been resolved in a more recent version of the extension. I will address this in https://github.com/deanoemcke/thegreatsuspender/issues/120

**Closed by deanoemcke** 2015-01-13 11:48 UTC
