### ISSUE TITLE
Please update this Plugin in the Google apps store

### ISSUE THREAD

**Issue by patrickhealy** [deanoemcke/thegreatsuspender#140] opened 2014-12-08 21:05 UTC
The version of this plugin up here works really well - it's not the one on the google apps store in Chrome. Can you PLEASE update the files so that the world can see your best work? Many people can't run developer mode or beta versions of the plugins. Thanks!

**Comment by patrickhealy** [comment] 2015-01-12 01:42
Please update. Pretty please, with sugar on top. :-)

**Comment by deanoemcke** [comment] 2015-01-12 07:56
ok ok ok. i'm seriously working on it. hoping this week to get it near ready. 
i know it seems to (and does) work much better than the current version on the store. just need to fix a couple of nasty bugs (that you may not have noticed) before i do.
sorry to keep everyone waiting. the end is in sight!

**Comment by patrickhealy** [comment] 2015-01-17 00:36
any word brother?

**Comment by deanoemcke** [comment] 2015-01-18 10:07
Yes. Getting there. Aiming for the end of the month.

**Comment by tjharman** [comment] 2015-01-25 23:44
I pledge to donate $10 to this project when the update rolls out :-)

**Comment by patrickhealy** [comment] 2015-02-10 04:29
Anything?

**Comment by deanoemcke** [comment] 2015-02-10 08:29
wow. is it the 10th of feb already? where does all the time go! working on it. promise.

**Comment by juristr** [comment] 2015-02-10 11:12
@deanoemcke I'm not sure what's holing you back from releasing it, but you should really switch to a "continuous delivery" mentality. 

- have a clean `master` (or production or whatever) branch that is **always** deployable.
- develop new features/bugfixes in separate feature/hotfix branches and only merge into master once finished (that helps to have a "clean" master branch)

When you have that one, I don't see any reason for holding back a release. Even if you have 10 planned features, you can release after the completion of each single feature. It's much more valuable to get early feedback and release often rather than wait, bundle together more features and have a larger, more feature-packed update (that even increases the risk of what could possibly wrong).

Hope you'll get it out soon...people start getting frustrated otherwise :wink:

**Comment by deanoemcke** [comment] 2015-02-10 11:15
@juristr 
thanks. yeah, i have realised that branches is the way to go. once this initial release is out i will head down that track. it's mainly because this release is a complete rewrite of the code from scratch, so there hasn't really been any iterative feature building.

**Comment by juristr** [comment] 2015-02-10 12:31
@deanoemcke I wrote an article a couple of month ago which we use internally: http://juristr.com/blog/2014/09/implementing-the-git-flow/

**Comment by patrickhealy** [comment] 2015-02-10 16:47
@deanoemcke I think I can speak for everyone in this project space when I say we LOVE this extension. Really, it has become my absolute must have extension. This and OneTab are critical to the way I work. The developers version I am using works fine for me and if you pushed that out I'd be fine with no update for MONTHS. Are there other things you can do? Of course. Will you make it better? Undoubtedly. But get that version out today so that the vast majority of these issues go away and you can get back to doing what you do on this thing. Here's an article that talks about how being a perfectionist can slow down progress. 

http://www.thenewsletterguru.com/perfection-kills-progress/

I'm with you brother, I want everything perfect. I just released a product that I already have the next 7 versions planned. But I need the data and feedback to make sure I can adjust the path to keep it most relevant. Come on, push that code buddy. We won't judge you for anything not "perfect". :-)

**Comment by juristr** [comment] 2015-02-10 17:06
@patrickhealy :+1:

**Comment by patrickhealy** [comment] 2015-02-20 06:09
I feel like this program and it's developer version ways are mocking me......

**Comment by Corrodias** [comment] 2015-02-20 17:27
I'm trying the beta now. It's quite useful. I had one bit of odd behavior, where it kept insisting my session had crashed when I closed tabs or navigated somewhere. I would appreciate the ability simply to disable the whole session management behavior entirely; I have a session manager extension for that, and the suspended tabs appear to function with it just fine.

But I'd say it's release-ready. It's functional and useful in this state.

**Comment by deanoemcke** [comment] 2015-02-20 19:28
@Corrodias I'm aware of that issue. I'm pretty sure I fixed it a few days back. Are you able to try the latest version and get back to me? The session stuff is really only there to help you recover lost tabs should the extension restart (or update). Other than that you should never really see the session recovery screen.

**Comment by Corrodias** [comment] 2015-02-20 19:41
The session restore tab also pops up almost every time I exit an later launch Chrome, as well. That is with 5.46 beta 1; if there's a way to get a newer one, I am not familiar with it.

**Comment by patrickhealy** [comment] 2015-02-20 19:56
So we're never getting this in the Google asp store then????

**Comment by Corrodias** [comment] 2015-02-20 20:01
The master branch still has the issue that the session recovery tab opens upon each launch. I'm not sure about the "when closing tabs" thing because I don't know exact steps to reproduce, but with a little bit of experimenting, I'm not seeing it happen.

**Comment by deanoemcke** [comment] 2015-02-20 20:21
@Corrodias what do you have set in your chrome->settings->on startup option?
ie. when chrome restarts, does it try to continue where you left off? or just start completely fresh?

**Comment by Corrodias** [comment] 2015-02-20 22:36
It is set to "open the new tab page".

**Comment by deanoemcke** [comment] 2015-02-22 11:19
@Corrodias 
i have decided to change the way the recovery works. it will now only prompt you to recover if the extension crashed but chrome remains open. if chrome itself crashes, then chromes own recovery functionality should restore the suspended tabs properly.
would be great if you could let me know if this feels more 'right' to you.

**Comment by juristr** [comment] 2015-02-22 11:46
how can I install the beta version? Directly from GitHub or is there
another way?

**Comment by patrickhealy** [comment] 2015-02-22 15:01
Well, if it was updated in the chrome extensions store like normal
extensions you could simply install it with a single click but.......

**Comment by deanoemcke** [comment] 2015-02-22 19:18
@juristr 
try following the instructions in the readme: https://github.com/deanoemcke/thegreatsuspender/blob/master/README.md

**Comment by Corrodias** [comment] 2015-02-22 21:11
@deanoemcke 
That model makes a lot of sense to me. I will try it out today.

**Comment by Corrodias** [comment] 2015-02-23 18:20
@deanoemcke 
It continues to believe the *extension* has crashed when I launch Chrome, whether I have some suspended tabs or not. If there is anything else about my environment that might affect this, I can give you a list of settings or extensions.

**Comment by deanoemcke** [comment] 2015-02-23 19:06
@Corrodias 
good point. i have started a new issue #155

**Comment by Corrodias** [comment] 2015-02-28 01:02
The author is working on #155. While it isn't fixed yet, it has been improved, and only doesn't work (in my limited experience) in an unusual edge case. I daresay it could be on the Chrome store, and I'm curious whether there are any arguments *against* publishing it.

**Comment by patrickhealy** [comment] 2015-02-28 01:48
No arguments here! Push that bad boy up there! :-)

**Comment by Barleyman** [comment] 2015-02-28 14:04
I second that motion. Just do it. There's always going to be polishing to be done. If you'll keep waiting for perfect version it'll literally never going to pass.
The current version is metric truckload better than the ancient version in store.

**Comment by patrickhealy** [comment] 2015-02-28 14:19
@Barleyman 
![image](https://cloud.githubusercontent.com/assets/9745486/6426481/d524cd40-bf2a-11e4-987c-87dd669f8af9.png)

**Comment by deanoemcke** [comment] 2015-03-06 09:20
I've been doing a bit of refactoring of the storage, and have moved to using indexedDB. Should be much faster now with storing and fetching suspended tab info.
There's a new beta available and would really appreciate you guys testing it out. Pending any major bugs, I'm hoping this will be releasable. 
https://github.com/deanoemcke/thegreatsuspender/releases/tag/v6.10-beta.1

**Comment by Aaron-Ritter-IDEXX** [comment] 2015-03-09 14:41
Updated to master as of today; my immediate impression is that it works well.

**Comment by Corrodias** [comment] 2015-03-09 22:43
Used it at work today. I couldn't tell any speed difference if there was one, but I didn't see anything break. :)

**Comment by Corrodias** [comment] 2015-03-13 05:25
Following up, I haven't seen any new issues pop up.

**Comment by borissamardzija** [comment] 2015-03-13 14:03
Beta works for me with no issues since you released it!

**Comment by juristr** [comment] 2015-03-15 21:15
Same here. Ready to be released! :+1:

**Comment by tjharman** [comment] 2015-03-15 21:18
Been working great.

**Comment by patrickhealy** [comment] 2015-03-16 04:49
SNORE!

**Comment by deanoemcke** [comment] 2015-03-16 05:02
@patrickhealy what. you don't have the new webstore version yet?

**Comment by tjharman** [comment] 2015-03-16 06:03
HOLY SHIT IT'S IN THE WEBSTORE.

I will now (well, Thursday when I get paid) donate $10 USD as promised above.

**Comment by deanoemcke** [comment] 2015-03-16 11:16
@tjharman hah. thanks. sorry it's been such a long time coming. feels good to finally get it out there.
i've only released to 5% of the users so far so not everyone will be receiving it as an update (not exactly sure quite how that process works).
will change it to 100% once i'm sure there's no angry people out there :)

**Comment by Barleyman** [comment] 2015-03-16 11:31
Apparently 4.74 does not want to automagically update or even manually. It MIGHT be because I also had the betas installed but the end result was that I had to uninstall 4.74 and then install the new version. In any case, no longer Chrome b*tching about developer extensions, that improved my quality of life by about 1.24%

**Comment by deanoemcke** [comment] 2015-03-16 19:17
@Barleyman it's currently only automatically updating 5% of users. uninstalling and reinstalling is fine as long as you don't mind losing your settings.

**Comment by Barleyman** [comment] 2015-03-16 19:44
"Update extensions now" button also does not do anything.

**Comment by liamjohnston** [comment] 2015-03-16 19:48
@Barleyman You are not part of the 5% it seems. If you remove the extension completely, then get it again from the webstore, you'll be away laughing. Note you may want to copy your whitelist before doing this.

**Comment by juristr** [comment] 2015-03-16 21:14
awesome :+1: 

And from now on, the GitHub model. Feature branches for everything and always a stable master s.t. one blocked feature/bug doesn't block the entire pipeline. Not that we end in this situation again :wink:

**Comment by deanoemcke** [comment] 2015-03-17 11:37
everybody. i have made some bug fixes after the first wave of feedback from the release. the latest version is now v6.13 and has been deployed to 10% of users.
those that have already upgraded to v6.12 will not get a new update screen - they should experience a silent update which will close and then restore suspended tabs automatically.
if you are in the latter position, i'd like to hear how the second update process went for you.

v6.13 contains new keyboard shortcuts. and improves the migration process from the older version v4.74. it also fixes some bugs around saving sessions in the session management tab.

**Comment by Aaron-Ritter-IDEXX** [comment] 2015-03-18 14:22
When the tabs are re-opened, are they moved to the positions that they were in before?

**Comment by deanoemcke** [comment] 2015-03-18 19:43
yes. it will look exactly as before.

**Comment by patrickhealy** [comment] 2015-03-20 16:25
Mine migrated over with relatively little effort. You just have to un-supend all tabs before you deactivate the older version and put in the new version then copy over the whitelist. 

@deanoemcke damn you for your stubbornness in not pushing out the older version(s) but great on you for turning this out in such good shape. It looks and works better than ever. Didn't think you could improve on this much but you did. Well done.

**Comment by deanoemcke** [comment] 2015-03-22 08:55
ok. even newer version is out. v6.14
hopefully this will be the last for a long while. i've identified and fixed a few edge case migration issues, as well as adding in the ability to delete saved sessions.
sorry if you are forced to undergo yet another extension reload (and suspended tab close and reopen). hopefully the new auto-recovery stuff is proving to be a smooth process for everyone.

**Comment by deanoemcke** [comment] 2015-05-10 02:19
A more recent version of the extension is now available in the chrome webstore. However, it has not been fully rolled out to all existing users (due to the potential of the update to cause users to lose some of their suspended tabs).
Not sure if I will ever fully push this out to all users. For now it will be available only for new users or people who uninstall and reinstall the extension. NOTE: if uninstalling then reinstalling, please unsuspend all tabs first. You will also lose any saved sessions so you might want to export them first.

**Closed by deanoemcke** 2015-05-10 02:19 UTC

**Comment by tjharman** [comment] 2015-05-11 05:41
I just uninstalled and reinstalled and still ended up with 6.14

Should I wait a few days or?

**Comment by deanoemcke** [comment] 2015-05-11 06:13
Sorry. That comment was referring to v6.14 as 'the more recent version' (for those still on v4.x).
I am hoping to get v6.15 (or higher) into the webstore soon, but I couldn't say exactly when yet. Sorry about that! Will keep you posted.
