### ISSUE TITLE
add option to start chrome with all tabs suspended right away?

### ISSUE THREAD

**Issue by zldrq** [deanoemcke/thegreatsuspender#117] opened 2014-08-10 05:52 UTC
hi! i wonder if you planning to add the option mentioned in subject?

i see a function called suspendAllTabsOnStartup in background.js, but how to enable it?

**Comment by deanoemcke** [comment] 2015-01-13 11:59
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/49.
Please add any new comments to that issue.

**Closed by deanoemcke** 2015-01-13 11:59 UTC
