### ISSUE TITLE
Add a "Never Suspend this path"

### ISSUE THREAD

**Issue by delacosta456** [deanoemcke/thegreatsuspender#566] opened 2017-07-25 16:05 UTC
hi
Please thanks for this nice module really helping us. 
Is it possible to add a "Never Suspend this path" on the list of option available when right click on icon of Google Chrome.

The existing "Never Suspend this site" add the domain of the site on which you are and not the Url

**Comment by deanoemcke** [comment] 2017-07-25 19:01
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/321

**Closed by deanoemcke** 2017-07-25 19:01 UTC
