### ISSUE TITLE
Rename "Screen Capturing" option

### ISSUE THREAD

**Issue by leesei** [deanoemcke/thegreatsuspender#238] opened 2015-06-18 04:21 UTC
I think "Show tab thumbnail" is more intuitive.
I did not understand what the screen capture function is.
I was only after checking the dependency html2canvas than I realized that it was for generating the tab thumbnail.

To be more explicit, it can be 
"Show tab thumbnail of suspended tab"

**Comment by deanoemcke** [comment] 2015-07-03 04:54
@leesei  I agree that screen capturing is not the most obvious wording. However, I doubt that many users would know what a thumbnail is. It's a pretty tech-oriented term. Also, thumbnail to me suggests a very small image, not a fullsize one. Other wording suggestions welcome..

**Comment by leesei** [comment] 2015-07-03 08:43
The screenshot is indeed scaled down, isn't it?
That's why I chose thumbnail instead of screenshot.

**Comment by deanoemcke** [comment] 2015-07-03 13:55
The screenshot should be exactly the same size as the contents of the webpage that was suspended. Are you finding something different? Could it be related to this issue #211?

**Comment by leesei** [comment] 2015-07-04 01:06
Oh, sorry. I misunderstood the feature then.
Maybe we can name it something like "keep screen content", "also freeze
screen".

**Comment by mwisnicki** [comment] 2015-11-21 16:26
I recommend "Show preview"

**Comment by fcherman** [comment] 2017-11-10 23:16
I think this problem is caused by an error I just discovered in the CSS. The culprit? A missing semicolon. See https://github.com/deanoemcke/thegreatsuspender/issues/622

**Comment by deanoemcke** [comment] 2017-11-27 14:36
Closing this as the confusion was most probably due to a bug (as pointed out by @fcherman )

**Closed by deanoemcke** 2017-11-27 14:36 UTC
Labels: enhancement
