### ISSUE TITLE
Restore only focused and pinned tabs on startup

### ISSUE THREAD

**Issue by aitchnyu** [deanoemcke/thegreatsuspender#263] opened 2015-07-29 07:12 UTC
As with Firefox default behavior, all tabs except pinned and focused tab should be suspended on startup. I currently use Footab along with GTS for this purpose. Please include it's functionality into GTS, since they dont tango well with each other.

**Comment by sldx** [comment] 2016-12-22 22:37
yes pls

**Comment by deanoemcke** [comment] 2017-07-25 17:44
Duplicate of issue: https://github.com/deanoemcke/thegreatsuspender/issues/49

**Closed by deanoemcke** 2017-07-25 17:44 UTC
