### ISSUE TITLE
feature request: favicon to display the suspended website's favicon instead of the great suspender's favicon

### ISSUE THREAD

**Issue by odotan** [deanoemcke/thegreatsuspender#860] opened 2019-02-08 12:22 UTC
feature request: favicon to display the suspended website's favicon instead of the great suspender's favicon.

All suspended tabs icons look the same (all with the great suspender's favicon). I would like the favicon in the tab to look either like the original website's favicon, or maybe a "suspended" version of that favicon (maybe a greyed out version of the site's favicon, or maybe the website's favicon with a badge on it indicating that it's suspended). In any case, I would like to be able to see which site the suspended tab has but right now I must open that tab (and possibly unsuspend it) to see what site it is. Thanks.

 * Extension version: 6.30
 * Browser name & version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
 * Operating system & version: MacOS Mojave 10.14.2 (18C54)

**Comment by Jollfye** [comment] 2019-02-08 16:29
I guess dev may soon push the 7.1 TGS extension update to Chrome Web Store and what u asking for is already an existing feature for a long time, even for 7.0.109 version that's now sitting there since August 25, 2018, tho it may be quite buggy, but it's all fixed with the latest dev 7.0.167 version for sure.

**Comment by deanoemcke** [comment] 2019-02-10 21:38
Sorry about this. It is a bug with the old version (v6.30) caused by a change in the code of chrome.
It is fixed in the current dev version and will be released to the webstore very shortly.

Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/719

**Closed by deanoemcke** 2019-02-10 21:38 UTC
