### ISSUE TITLE
Feature suggestion: Cache page when suspending, so the extension can load again without downloading

### ISSUE THREAD

**Issue by OHermesJunior** [deanoemcke/thegreatsuspender#798] opened 2018-10-21 21:57 UTC

**Comment by deanoemcke** [comment] 2018-10-26 18:41
This is a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/265 and https://github.com/deanoemcke/thegreatsuspender/issues/220

**Closed by deanoemcke** 2018-10-26 18:41 UTC
