### ISSUE TITLE
Issue with youtube subscriptions page

### ISSUE THREAD

**Issue by Bl4ckDoT** [deanoemcke/thegreatsuspender#543] opened 2017-06-22 20:05 UTC
I have to constantly clear cookies history to fix this issue. 
![chrome_2017-06-22_16-03-35](https://user-images.githubusercontent.com/11063272/27453459-8c2df1fa-5764-11e7-8f9f-04797d85b5b6.png)

**Comment by H0R1Z0N** [comment] 2017-06-22 20:31
This start to becoming annoying to wait for a fix. I used this plugin for more than a year and the dev's previous alpha test plugin from before he make that one.

**Comment by Bl4ckDoT** [comment] 2017-06-23 23:45
I use the subscription feature a lot and I'm torn between uninstalling TGSuspender or keeping it. It's extremely annoying.

**Comment by H0R1Z0N** [comment] 2017-06-23 23:51
Well, i will try to compile a previous build from some year ago, you would be able to sideload it.

**Comment by ToastedJelly** [comment] 2017-06-25 09:23
Same issue here. It spams www.youtube.com with "gsScrollPos-#####" cookies till youtube is showing the malformed request error. 
Storing this kind of information in the cookies looks like a quick hack solution to me - the website shouldn't even be made aware that I'm using GS - the scroll position should be stored togetber with the URL.

**Comment by deanoemcke** [comment] 2017-07-23 01:33
Im not sure why i ever decided to implement the scroll position using cookies :(
Storing it in the url makes sense. I'll adjust the code i've [already written](https://github.com/deanoemcke/thegreatsuspender/commit/50b6e77de8dd3dbd8a8444c91785e5074eb295f9) to solve this issue.

**Comment by deanoemcke** [comment] 2017-07-23 01:34
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/537

**Closed by deanoemcke** 2017-07-23 01:34 UTC
