### ISSUE TITLE
[x] do not auto-suspend tab if audio is played in this tab <-- option request

### ISSUE THREAD

**Issue by LynXSPb** [deanoemcke/thegreatsuspender#132] opened 2014-10-24 19:18 UTC
[x] do not auto-suspend tab if audio is played in this tab <-- option request

Explanation:
I often run some youtube video in background unfocused tab(mostly listening music, google talks, or some talkative documentary), and TGS with inactivity timer set up, sometimes suspends them which is undesirable.

If TGS already recognizing unfocused tabs with active audio as an active tabs, maybe it is a bug.

**Comment by Akahadaka** [comment] 2015-02-05 02:55
Perhaps an alternative to this request is to have an option to mark a tab as an **exception**. The exception tab will not suspend as long as the tab is "alive", but the URL is not stored in settings, so when the tab is closed and the same URL is re-opened, it will resume suspending as normal.

*"Do not suspend pinned tabs"* (which I think is complete) is another alternative, but in my case I'm quite happy for most of my pinned tabs to auto-suspend. I just need to make exceptions every once in a while, like the YouTube example given above.

**Comment by deanoemcke** [comment] 2015-02-10 14:00
@Akahadaka 
I have actually already implemented this. Check out the 'pause suspension' button in the popup menu (of the latest github version). It will temporarily pause suspension of the page.

**Comment by Akahadaka** [comment] 2015-02-11 15:54
Installed and can confirm exceptions (pausing) is working great! Thanks!

**Comment by deanoemcke** [comment] 2015-05-10 05:47
duplicate of issue #28.

**Closed** 2015-05-10 05:47 UTC
