### ISSUE TITLE
Settings window overrides the first suspended tab

### ISSUE THREAD

**Issue by MeiRct** [deanoemcke/thegreatsuspender#251] opened 2015-07-06 17:31 UTC
When entering settings in a window that has suspedned tab(s), it overrides the first suspended tab in the window, instead of opening in new tab.

**Comment by chadjefferies** [comment] 2015-07-14 16:20
I have noticed this as well. There appears to be two different ways to get to the settings page. Right clicking the icon and selecting Options overrides the first tab instead of opening in a new window. Left clicking the icon and selecting Settings DOES properly open in a new tab.

**Comment by MeiRct** [comment] 2015-07-14 17:24
@chadjefferies you're right, thanks for the tip.
I think the issue with the right click might be related to Chrome browser itself, trying to load the first "chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/" page it sees, as it does while loading any "chrome://" page (like settings or downloads). 
I assume it tries to avoid a duplication of these special pages, including extentions.

**Comment by deanoemcke** [comment] 2015-08-11 03:20
Closing as duplicate of issue #222

**Closed by deanoemcke** 2015-08-11 03:20 UTC
