### ISSUE TITLE
Configurable delay when auto-unsuspending a tab that gains focus

### ISSUE THREAD

**Issue by wwwhttp** [deanoemcke/thegreatsuspender#630] opened 2017-12-17 14:59 UTC
Suspended tabs need too long to start unsuspending after it is beeing viewed

**Comment by liamjohnston** [comment] 2017-12-17 20:50
There is a delay. I can't remember how long exactly, but it is by design (AND was requested by other GitHub users I'm pretty sure). Reason being: a very brief focus doesn't necessarily imply intention to view the tab. 

For instance: I often switch between tabs with my arrow keys (cmd + option + left/right), skipping over one or two suspended tabs to get to another tab. I'm not interested in those skipped suspended tabs so they should stay suspended. 

How long would you say it's taking before it appears to start reloading? Perhaps we could look at adjusting this. I think no more than 1 second should be about right for the 'keyboard tabbing' scenario above.

**Comment by wwwhttp** [comment] 2017-12-21 22:25
Sorry for the delayed response,

Yes, it definitely makes sense, if you are using shortcuts for the switching between tabs. I think the delay is about 1 sec. Maybe it would be possible to move this feature to the settings?

Some other "bug" is that if you close some tab and the browser automatically switches to the next tab (which is suspended), this tab stays suspendend, does it make sense?

**Comment by liamjohnston** [comment] 2017-12-21 22:31
On that last part, see https://github.com/deanoemcke/thegreatsuspender/issues/519

**Comment by draarong** [comment] 2018-05-11 23:39
Agree on wish to have unsuspend delay setting as preference :)

**Comment by ossilator** [comment] 2019-03-04 18:17
seems like a straight duplicate of #252, no?

**Closed** 2019-03-04 20:44 UTC
Labels: duplicate, feature
