### ISSUE TITLE
Add regex rules list for suspending tabs that contain unsaved form inputs

### ISSUE THREAD

**Issue by adcurtin** [deanoemcke/thegreatsuspender#815] opened 2018-11-16 18:16 UTC
I have a massive problem with Google Keep, but the likelihood of google fixing it is 0. however, I think I can fix it with TGS.

I would really like options to prevent TGS from suspending some tabs that have unsaved form input, but still allow it to suspend others. E.g. I would add keep.google.com to the list of sites that will be suspended regardless of unsaved form input.

(In my case, I'd much rather I lose even 5 items I type into a list, than to have keep rearrange the 100+ item list randomly with no wya to recover)

### Specifications:
 * Extension version: latest
 * Browser & version: chrome 70.0.3538.77
 * Operating system & version: macos 10.14.1

**Comment by deanoemcke** [comment] 2018-11-19 10:54
@adcurtin could you elaborate on your problem with google keep a bit?
to be clear, you're wanting google keep to suspend even though it has unsaved form input, but don't want to uncheck this option as you still want other form input tabs to prevent automatic suspension?

this most likely a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/705

**Comment by adcurtin** [comment] 2018-11-19 17:32
google Keep randomly rearranges my note that has 400+ items in it, if more than 1 device is accessing the note at a time. Sometimes, I don't remember to close the keep tab on my home computer before leaving home.

If there is text entered, TGS won't suspend the keep tab. If I have TGS suspend it anyway, I might lose maybe 5 things I typed in maximum. that is significantly better than rearranging 400 items. So if TGS suspends Keep tabs after the idle period, regardless of entered input, it should prevent this nasty keep bug from happening.

I agree, this does look like a dupe of #705 .

**Closed** 2018-11-20 01:16 UTC
Labels: duplicate
