### ISSUE TITLE
"Suspend this tab now" sometimes doesn't work

### ISSUE THREAD

**Issue by Harmon758** [deanoemcke/thegreatsuspender#735] opened 2018-08-26 00:19 UTC
"Suspend this tab now" in the popup UI from clicking the extension icon sometimes does nothing.
Most of the time, reopening the popup and clicking it again causes it to suspend properly.
I'm not sure what's causing it or how to reproduce the issue consistently. It happens across different pages and sites and there's no errors in the console or on the extensions page.
I'm unable to reproduce the issue with "Suspend/Unsuspend this tab" in the context menu.
I'm also not sure how to debug it further, but I'm more than willing to try any steps provided to do so.

### Specifications:
 * Extension version: v7.0.109 (Also experienced on v7.0.104)
 * Browser & version: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 * Operating system & version: Microsoft Windows 7 (64-bit) [Version 6.1.7601]

**Comment by Harmon758** [comment] 2018-08-27 09:55
@roastchicken No, I have Screen Capturing disabled.
That seems to be a separate known issue. See #657.

**Comment by roastchicken** [comment] 2018-08-27 11:48
Hmmm, interesting. Thank you for the info, I'll have to check out that other issue.

**Comment by SnIPeRSnIPeR** [comment] 2018-08-27 19:06
I have the same issue on v.7 right now! Had this problem on v.6: https://github.com/deanoemcke/thegreatsuspender/issues/574

See the video!

**Comment by SnIPeRSnIPeR** [comment] 2018-08-28 14:58
Any suggestions?

**Comment by Harmon758** [comment] 2018-08-28 15:25
This also seems to be a separate issue.

**Comment by deanoemcke** [comment] 2018-08-29 20:18
@SnIPeRSnIPeR i'm sorry, i don't fully understand what is happening for you. can you open a separate issue and explain in detail what you are experiencing?

@Harmon758 i am still investigating your issue of 'Suspend this tab now' intermittently not working from the popup menu. As you can imagine, it's not the easiest thing to test. Although anecdotally, i feel like i've experienced this myself once or twice.

**Comment by deanoemcke** [comment] 2018-10-04 02:56
@Harmon758 @roastchicken @SnIPeRSnIPeR if any of you are running a development version of the extension, i have just pushed an optimistic fix for this issue (v7.125).

Let me know if the problem seems to be resolved.

FYI, it was potentially caused by some code that cancels a suspend tab request if the tab being suspended somehow _regains_ focus before the suspension finishes.
It's possible that this is somehow happening due to the popup menu opening and closing.

**Comment by Harmon758** [comment] 2018-10-04 22:49
Seems to be fixed in v7.125.
Haven't had any issues with it thus far.

**Comment by SnIPeRSnIPeR** [comment] 2018-10-11 16:47
Waiting for release on Chrome Web Store! :)

**Closed** 2019-02-06 04:05 UTC
Labels: bug-confirmed, prioritised, waiting-on-release
