### ISSUE TITLE
Bunch of sites have recently stopped suspending

### ISSUE THREAD

**Issue by m16p** [deanoemcke/thegreatsuspender#661] opened 2018-02-22 01:50 UTC
I noticed this on various google.com sites (Drive, Flights, Keep, Photos, Docs, etc).  It worked a month ago, now it doesn't.  I hit Ctrl-Shift-S and nothing happens.  Right click and select "Suspend Tab" and nothing happens.  No messages in the developer console that I can see.

Others have reported this on other sites:  https://github.com/deanoemcke/thegreatsuspender/issues/660 and https://github.com/deanoemcke/thegreatsuspender/issues/657.

Any idea why it isn't working?  There are no unsaved form entries, no audio being played, the tabs aren't pinned, and they aren't whitelisted either...

**Comment by kcanini** [comment] 2018-03-03 22:56
Same here.

**Comment by deanoemcke** [comment] 2018-03-14 16:16
Is it possibly related to this issue? #646
What version of chrome are you using and what version of the extension?
I have been unable to reproduce this :(

**Comment by kcanini** [comment] 2018-03-14 17:21
I'm running TGS v6.30 on Mac OS 10.13.3 and Chrome 64.0.3282.186.

I am consistently unable to suspend Google Spreadsheets webpages, and the TGS menu is different from what it normally looks like: https://imgur.com/a/B4SQ7

**Comment by deanoemcke** [comment] 2018-03-15 15:11
@kcanini while on the google spreadsheets tab, if you right-click on the extension icon and select 'inspect popup' do you see any errors in the console of the developer tools window that appears?

**Comment by kcanini** [comment] 2018-03-15 15:24
No, there are no errors.

**Comment by deanoemcke** [comment] 2018-03-15 15:46
And what about the console of the google sheets tab itself?
And if you go into chrome://extensions, enable developer mode, then inspect the background page for the extension, are there any errors in the console there?

Finally, do you still have the problem if you refresh the google sheets tab?
And how about after closing the tab, and then reopening it.
Is it a regular google sheets page? (ie. a spreadsheet you are working on)

**Comment by kcanini** [comment] 2018-03-15 15:58
No errors in the main page's console either.

I already had developer mode on. What is the difference between "the background page for the extension" and when I right-click on the extension icon and select 'inspect popup'?

Yes, I have the problem with every spreadsheet, every time I load it or reload it.

It is a regular spreadsheet page that I am working on.

**Comment by deanoemcke** [comment] 2018-03-15 16:35
afaik, when you inspect the popup, that's just the scope of the popup page itself. if it's the popup throwing errors, they will appear in the console there, not in the console of the extension's background_page.

one more thought. are you using enterprise google docs? i forgot about it but there was another person having a very similar issue to you: #591

sorry for only mentioning this now!

**Comment by kcanini** [comment] 2018-03-15 17:03
There are no errors in the console for the background page either.

I have enterprise google docs on my other Chrome profile, and TGS is also broken for google spreadsheets on that profile. But this profile is a regular personal account.

**Comment by erikkkerikkk** [comment] 2018-03-20 01:03
I didn't notice this extension was not working until my Chrome crashed. For those who is looking for a quick workaround, I would suggest to download the old portable version.

https://sourceforge.net/projects/osxportableapps/files/Chromium/
Chromium_OSX_63.0.3239.132.dmg

**Comment by deanoemcke** [comment] 2018-08-21 03:52
Even though I cannot reproduce, I will assume that this issue will be made redundant by the upcoming release v7.x

Will most likely be addressed in the fix to: https://github.com/deanoemcke/thegreatsuspender/issues/591

**Closed** 2019-02-06 04:05 UTC
Labels: bug-unconfirmed, waiting-on-release
