### ISSUE TITLE
hiding chrome's windows windows 10

### ISSUE THREAD

**Issue by AkramBazerbashi** [deanoemcke/thegreatsuspender#1073] opened 2019-12-15 20:47 UTC
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.0
 * Browser name & version: chrome  79.0.3945.79
 * Operating system & version: win10 1909

And please also do a search for your request/bug before create a new one thanks!
when restarting my windows 10 and launching chrome and press restore tabs, it didn't show all  
chrome windows, and when trying to see what suspender has, it show number of windows higher than the actual running

**Comment by q00u** [comment] 2019-12-17 23:47
Duplicate of #1070 / #1071 ?

Bug in Chrome, not Great Suspender.

Should already be fixed in Chrome 79.0.3945.88. Help | About | Update | Relaunch

**Closed** 2019-12-17 23:56 UTC
