### ISSUE TITLE
Resume from cache

### ISSUE THREAD

**Issue by dsvensson** [deanoemcke/thegreatsuspender#220] opened 2015-06-02 12:24 UTC
It would be great if resuming would load the page from the cache and not The Internets if you happen to be on a train in the middle of nowhere when you notice you forgot to whitelist a page you intended to read.

**Comment by deanoemcke** [comment] 2015-06-08 05:32
The extension does not explicitly request a hard reload, so I had assumed that it would be doing cached reloads. As far as I am aware, I'm not able to explicitly request that the page reloads from cache?
I came across this article: http://addyosmani.com/blog/offline-mode-chrome/
Perhaps that could be a solution for you?

**Comment by deanoemcke** [comment] 2015-09-26 06:23
Closed as duplicate of #265

**Closed by deanoemcke** 2015-09-26 06:23 UTC
