### ISSUE TITLE
"Unsusped all tabs" does nothing

### ISSUE THREAD

**Issue by vinyar** [deanoemcke/thegreatsuspender#392] opened 2016-04-28 01:14 UTC
version v6.21
Suspender is set to 12 hours

Use case:
I usually have around 4 chrome windows with around 10-15 tabs each. 
As far as I can tell, `unsuspend all tabs` does not unsuspend any of the tabs in any of the windows.

Request:
Please fix this, without this feature functioning, user has to go through countless tabs and click, click, click, click, click, click, click, click...

**Comment by hamsternik** [comment] 2016-05-24 19:12
I got this bug behaviour with a lot of opened tabs in chrome (amount of tabs was more 20).  When i clicked on "Unsuspend all tabs", it makes nothing.

But, accidentally, when i suspended in new chrome window some tabs (general amount was small, maybe 6 tabs in all), and then push on ususpend shortcut, suddenly, they all wake up.

**Comment by andreolli** [comment] 2016-10-06 02:03
Sometimes I get this bug also, I am using Windows 8.1 and Chrome 53.0.2785.116 m.

**Comment by deanoemcke** [comment] 2017-07-25 19:24
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/361

**Closed by deanoemcke** 2017-07-25 19:24 UTC
