### ISSUE TITLE
All Pages in Chromes Cross Computer History Show as Suspended Tab

### ISSUE THREAD

**Issue by CultD** [deanoemcke/thegreatsuspender#440] opened 2016-10-04 04:07 UTC
It's very inconvenient when trying to use google Chromes Cross Computer History and Great Suspender. 
The Great Suspender should make the page name, Suspended Tab (suspended pages name). or (suspended pages name) Suspended tab, or (suspended pages name).

**Comment by deanoemcke** [comment] 2017-10-23 18:14
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/46

**Closed by deanoemcke** 2017-10-23 18:14 UTC
