### ISSUE TITLE
Suspended tab favicons not persisting through restart.

### ISSUE THREAD

**Issue by Dreams-Visions** [deanoemcke/thegreatsuspender#772] opened 2018-10-03 12:03 UTC
### Specifications:
 * Extension version: **6.30**
 * Browser & version: **Google Chrome v. 69.0.3497.100**
 * Operating system & version: **Windows 10 Pro, 10.0.17763, Build 177163 and OSX High Serria 10.13.6**

Warmest greetings and thank you for the fantastic plug-in. I've been using it for years and have always been happy with it. One issue I've noticed on the latest version of Chrome (with the new UI update) on both Windows 10 and OSX is that when Chrome is restarted, favicons never change from the Great Suspender temporary favicon back to the actual website favicon as they did consistently before this Chrome update.  

**Summary:** Typically website Favicons appear for all websites and appear faded to indicate the tab is asleep when using The Great Suspender. They correctly do this for new tabs that fall asleep or if tabs are unsuspended and allowed to go back to sleep. Unfortunately, when Chrome is restarted (say, due to a system restart) and Chrome is re-opened with the full session opened, all suspended tabs show the great suspender favicon and never update to the actual website favicon as they used to. The only solution right now is to unsuspend all tabs again and wait for them to go back to sleep. Again, this is true on both Window 10 and OSX for me. 

Because of the number of tabs I have open seeing those favicons is essential, so if this can be looked into and resolved, that would be awesome.

Thank you in advance.

**Comment by Dreams-Visions** [comment] 2018-10-03 12:06
Note: I just noticed that Chrome never updated my version of TGS for some reason. I have installed the most recent version and will report back if the issue is resolved. Otherwise, please assume the issue persists.

**Comment by deanoemcke** [comment] 2018-10-04 02:59
This is most likely a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/719

Should be fixed in the new release!

**Closed** 2018-10-11 01:18 UTC
Labels: duplicate
