### ISSUE TITLE
Tabs are suspended before loading on chrome startup

### ISSUE THREAD

**Issue by 4evermaat** [deanoemcke/thegreatsuspender#359] opened 2016-01-20 06:04 UTC
There was an extension called FooTab that allowed the user to suspend the tabs on chrome restart (when you have 'reload tabs from last time' option selected in Chrome options).  But that extension seems to be broken now as the developer has not provided an update for some time (and Google either disabled it or changed their browser so that it is unlikely it will work in the future.)

Anyway, I would really like to see this happen with the great suspender.  An ability to stop all tabs loading from a previous session.  Only the current tab is loaded, and all non-current tabs are suspended immediately when Chrome starts (not loaded first and then suspended....that makes no sense).

Thanks for consideration.

**Comment by zionyx** [comment] 2016-02-04 09:23
+1 to this feature.

**Comment by piranna** [comment] 2016-02-04 15:14
Probably this is the most useful feature to have...

**Comment by hackel** [comment] 2016-12-13 23:04
Dupe of #49, please close @4evermaat .

**Closed** 2017-07-25 17:47 UTC
