### ISSUE TITLE
FeatureReq: Start tabs in suspended mode and suspended tabs lifespan

### ISSUE THREAD

**Issue by JonasSanderhall** [deanoemcke/thegreatsuspender#284] opened 2015-08-31 12:58 UTC
Feature 1: Start in suspended mode.
I would like to have an option to start the tab in suspended mode instead of having chrome struggle with loading all tabs at once. This will ease the load when opening chrome when your are a tab junkie :)

Feature 2:
Set a lifespan in suspended tabs. If a tab has been suspended for more then X hours automatic close it. This will clear unused tabs that you dont revisit in time.

Ps. Excellet addon! Keep up the good work! Ds

**Comment by jpluimers** [comment] 2015-09-18 06:56
Better make this 2 feature requests so they can be tracked independently. Do you mind if I request the first as a separate one (it's high on my wish list; I regularly have 100+ tabs open which means that restarting chrome can take a a very long while consuming a truckload of memory).

**Comment by deanoemcke** [comment] 2015-09-26 06:04
Request 1 is a duplicate of issue #49. And request 2 is a duplicate of issue #281.
@JonasSanderhall You might want to add your idea of making the tab closing automatic to that other issue.

**Closed by deanoemcke** 2015-09-26 06:04 UTC
