### ISSUE TITLE
Feature request: Tab suspend and offline content

### ISSUE THREAD

**Issue by Karthik1982** [deanoemcke/thegreatsuspender#341] opened 2015-12-16 11:08 UTC
Currently this plugin is suspending the tab and reloading it again and it is a kind of handy bookmark feature. Once the tab is suspended and the machine is offline and it needs to be un-suspended then the tab re-opening will fail. 

_It would be nice if it has an option to suspend the tab by caching all its current page offline_ and reload it once the tab is un-suspended. This will also reduce the unwanted network traffic of loading the same page again.

**Comment by EleanorEllis** [comment] 2017-11-01 01:35
This used to be an option, but it has been removed for some reason.

**Comment by deanoemcke** [comment] 2017-11-03 00:53
This sounds like a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/265
Please refer to that issue as to the feasibility of this feature request.

@EleanorEllis I have never implemented this feature. Are you referring to screen capturing perhaps?

**Closed by deanoemcke** 2017-11-03 00:53 UTC
