### ISSUE TITLE
Open link in new tab (suspended)

### ISSUE THREAD

**Issue by KivesJM** [deanoemcke/thegreatsuspender#255] opened 2015-07-13 10:53 UTC
I would like to add this as a request rather than an issue but I have no idea how to do it.

It would be nice if you could right click a link and select 'Open Link in New Tab (Suspended)'.

This would allow me to build up a list of items (e,g, news stories) that I would then open and close one at a time.

Thanks,

Kevin

**Comment by deanoemcke** [comment] 2015-07-15 02:14
Hi,
Thanks for the suggestion. It's a great one which does have a few issues.
It is a feature that has already been requested so I will close this as a duplicate of #228

**Closed by deanoemcke** 2015-07-15 02:14 UTC
