### ISSUE TITLE
Feature request: Save session in the dropdown menu

### ISSUE THREAD

**Issue by rnand** [deanoemcke/thegreatsuspender#299] opened 2015-09-15 06:58 UTC
Why is the 'Save session' option hidden deep in the settings page? Why not add an option to save the current session in the dropdown menu? Like this:
![session](https://cloud.githubusercontent.com/assets/12506856/9869890/3cc15538-5ba5-11e5-8bd4-d2a72fcabcc6.PNG)

**Comment by deanoemcke** [comment] 2017-08-31 01:56
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/419

**Closed by deanoemcke** 2017-08-31 01:56 UTC
