### ISSUE TITLE
No longer unsuspends when viewed

### ISSUE THREAD

**Issue by adefaria** [deanoemcke/thegreatsuspender#523] opened 2017-06-07 16:43 UTC
The "Automatically unsuspend tab when it is viewed" suddenly no longer works.

Version: 6.30

**Comment by poulhansen** [comment] 2017-06-08 07:46
It's the same here although sometimes it works.
It happened after my screen showed an "update" to the program.

**Comment by deanoemcke** [comment] 2017-06-08 15:18
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/519

**Closed by deanoemcke** 2017-06-08 15:18 UTC
