### ISSUE TITLE
Option to suspend all tabs upon exit of Chrome

### ISSUE THREAD

**Issue by iliawnek** [deanoemcke/thegreatsuspender#157] opened 2015-03-07 23:11 UTC
I have Chrome set to remembering all open tabs, but I usually don't need all of them immediately when I startup Chrome. It would be really useful if I could set all open tabs to be suspended automatically when I close down Chrome, so that the next time I open Chrome, I can choose which tabs to un-suspend and which tabs to close. Plus, if I'm just opening Chrome to make a quick search or check a site briefly, Chrome won't need to reload every single app, making the process much faster.

**Comment by deanoemcke** [comment] 2015-03-09 19:29
This has been requested before in issue #49 in a slightly different way. Unfortunately, I cannot see an easy way of detecting when a user closes chrome. If someone knows how this might be possible I'd look into implementing this.
As a workaround for now, just use the 'suspend other tabs' button to manually suspend the window before you close it.

**Comment by thecrazy** [comment] 2015-09-26 20:46
There may be a way to do it if you are able to interact with chrome before it loads all its tabs. This addon somehow manages to do it but its developper kind of abandoned it so no new features. https://chrome.google.com/webstore/detail/footab/anbodogikfbehidmmjdokehphginagbb?utm_source=chrome-app-launcher-info-dialog

**Comment by deanoemcke** [comment] 2015-11-13 05:07
Closing this issue as it is essentially a duplicate of #49. The only reason you would want to suspend tabs before closing chrome is so that chrome loads faster on startup next time.

**Closed by deanoemcke** 2015-11-13 05:07 UTC
